import { eq } from "drizzle-orm";
import { getDb } from "@/db";
import { campaignRates, campaigns } from "@/db/schema";
import { requireAdmin } from "@/lib/auth/guards";
import { requireSameOrigin } from "@/lib/security/origin";

const allowed={DRAFT:["REVIEW","ARCHIVED"],REVIEW:["DRAFT","ACTIVE","ARCHIVED"],ACTIVE:["PAUSED","COMPLETED"],PAUSED:["ACTIVE","COMPLETED","ARCHIVED"],COMPLETED:["ARCHIVED"],ARCHIVED:[]} as const;
type Status=keyof typeof allowed;

export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){try{requireSameOrigin(request);await requireAdmin();const{id}=await params;const body=await request.json();const next=String(body.status??"") as Status;if(!(next in allowed))return Response.json({ok:false,error:"INVALID_STATUS"},{status:400});const db=getDb();const result=await db.transaction(async tx=>{const locked=await tx.execute<{status:Status;start_at:Date|null;end_at:Date|null}>(`select status,start_at,end_at from campaigns where id='${id.replace(/'/g,"''")}' for update`);const row=locked.rows[0];if(!row)throw new Error("NOT_FOUND");if(!(allowed[row.status] as readonly string[]).includes(next))throw new Error("INVALID_TRANSITION");if(next==="ACTIVE"){const[rate]=await tx.select().from(campaignRates).where(eq(campaignRates.campaignId,id)).limit(1);if(!rate||rate.advertiserRate<=0||rate.partnerBaseRate<0||rate.partnerBaseRate+rate.minimumMargin>rate.advertiserRate)throw new Error("RATE_NOT_READY");const now=new Date();if(row.end_at&&row.end_at<=now)throw new Error("CAMPAIGN_ENDED");}const[updated]=await tx.update(campaigns).set({status:next,updatedAt:new Date()}).where(eq(campaigns.id,id)).returning({id:campaigns.id,status:campaigns.status});return updated;});return Response.json({ok:true,campaign:result});}catch(error){const code=error instanceof Error?error.message:"UPDATE_FAILED";const status=code==="INVALID_ORIGIN"||code==="ORIGIN_CHECK_FAILED"?403:code==="NOT_FOUND"?404:code==="INVALID_STATUS"?400:409;return Response.json({ok:false,error:code},{status});}}
