import Link from 'next/link';import {and,desc,eq,sql} from 'drizzle-orm';import {redirect} from 'next/navigation';import DashboardShell from '@/components/DashboardShell';import ReadAllNotifications from '@/components/ReadAllNotifications';import NotificationReadButton from '@/components/NotificationReadButton';import {getDb} from '@/db';import {notifications} from '@/db/schema';import {getCurrentUser} from '@/lib/auth/session';import './notifications.css';
export const dynamic='force-dynamic';
const labels:Record<string,string>={BALANCE_LOW:'광고비 잔액',CPA_APPROVAL_REQUEST:'CPA 승인 요청',CPA_REJECTION_REQUEST:'CPA 반려 요청',CPA_REVIEW:'CPA 검수',NEW_CPA_DB:'새 CPA 접수',POSTING_REVIEW:'포스팅 검수',POSTING_SUBMITTED:'포스팅 제출',SETTLEMENT_REQUEST:'출금 신청',SETTLEMENT_REVIEW:'출금 처리',QUICK_REVIEW:'1초알바 검수'};
export default async function Page({searchParams}:{searchParams:Promise<{status?:string|string[]}>}){
 const user=await getCurrentUser();if(!user)redirect('/login?next=/notifications');if(user.status!=='ACTIVE')redirect('/login?error=account_not_active');const params=await searchParams,status=params.status==='unread'||params.status==='read'?params.status:'all',db=getDb();
 const [rows,[stats]]=await Promise.all([db.select().from(notifications).where(and(eq(notifications.userId,user.id),status==='all'?undefined:eq(notifications.isRead,status==='read'))).orderBy(desc(notifications.createdAt)).limit(100),db.select({total:sql<number>`count(*)`,unread:sql<number>`count(*) filter (where ${notifications.isRead}=false)`}).from(notifications).where(eq(notifications.userId,user.id))]);
 const unread=Number(stats?.unread??0),total=Number(stats?.total??0),home=user.role==='PARTNER'?'/partner':user.role==='ADVERTISER'?'/advertiser':'/admin';
 return <DashboardShell title="알림센터" description={`읽지 않은 알림 ${unread}건`} nav={[{href:home,label:'← 대시보드'},{href:'/notifications',label:'알림센터'}]}><section className="panel card"><div className="page-toolbar"><div><h1 className="nt-title">알림센터</h1><p className="muted">읽지 않은 알림 {unread}건 · 전체 {total}건</p></div>{unread>0&&<ReadAllNotifications/>}</div><nav className="nt-filters" aria-label="알림 상태">{[{key:'all',label:'전체',count:total},{key:'unread',label:'미읽음',count:unread},{key:'read',label:'읽음',count:total-unread}].map(x=><Link key={x.key} href={x.key==='all'?'/notifications':`/notifications?status=${x.key}`} aria-current={status===x.key?'page':undefined}>{x.label} {x.count}</Link>)}</nav><p className="muted">선택한 상태의 최신 {rows.length}건을 표시합니다. 최대 100건까지 볼 수 있습니다.</p><div className="notification-list">{rows.length?rows.map(n=><article key={n.id} className={`notification-item ${n.isRead?'':'unread'}`}><div><span className="badge">{labels[n.type]??'서비스 알림'}</span>{!n.isRead&&<span className="unread-dot">NEW</span>}<h3>{n.title}</h3><p className="nt-message">{n.message}</p><small className="muted">{n.createdAt.toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</small></div>{(n.href||!n.isRead)&&<NotificationReadButton id={n.id} hasLink={Boolean(n.href)}/>}</article>):<p className="empty-cell">{status==='unread'?'읽지 않은 알림이 없습니다.':status==='read'?'읽음 처리한 알림이 없습니다.':'아직 받은 알림이 없습니다.'}</p>}</div></section></DashboardShell>;
}
