import DashboardShell from "@/components/DashboardShell";
import CampaignStatusActions from "@/components/CampaignStatusActions";
import { and, desc, eq, isNull } from "drizzle-orm";
import { notFound } from "next/navigation";
import { getDb } from "@/db";
import { advertisers, campaignRates, campaigns } from "@/db/schema";
import { requireAdmin } from "@/lib/auth/guards";

export const dynamic="force-dynamic";
const nav=[{href:"/admin",label:"대시보드"},{href:"/admin/partners",label:"파트너 관리"},{href:"/admin/advertisers",label:"광고주 관리"},{href:"/admin/campaigns",label:"캠페인 관리"},{href:"/admin/conversions",label:"전환 DB"},{href:"/admin/posting",label:"포스팅 작업"},{href:"/admin/ledger",label:"광고비·수익"},{href:"/admin/settlements",label:"정산"}];
const won=(n:number|null|undefined)=>`${(n??0).toLocaleString("ko-KR")}원`;
const date=(d:Date|null)=>d?d.toLocaleString("ko-KR"):"제한 없음";
export default async function Page({params}:{params:Promise<{id:string}>}){await requireAdmin();const{id}=await params;const db=getDb();const[row]=await db.select({id:campaigns.id,code:campaigns.campaignCode,type:campaigns.type,name:campaigns.name,slug:campaigns.slug,category:campaigns.category,description:campaigns.description,status:campaigns.status,startAt:campaigns.startAt,endAt:campaigns.endAt,dailyConversionLimit:campaigns.dailyConversionLimit,monthlyConversionLimit:campaigns.monthlyConversionLimit,dailyBudgetLimit:campaigns.dailyBudgetLimit,monthlyBudgetLimit:campaigns.monthlyBudgetLimit,duplicateDays:campaigns.duplicateDays,reviewDays:campaigns.reviewDays,company:advertisers.companyName,createdAt:campaigns.createdAt}).from(campaigns).leftJoin(advertisers,eq(campaigns.advertiserId,advertisers.id)).where(eq(campaigns.id,id)).limit(1);if(!row)notFound();const[rate]=await db.select().from(campaignRates).where(and(eq(campaignRates.campaignId,id),isNull(campaignRates.effectiveTo))).orderBy(desc(campaignRates.effectiveFrom)).limit(1);return <DashboardShell title={row.name} description={`${row.type} 캠페인 상세 및 운영 설정`} nav={nav}><div className="page-toolbar"><a className="btn" href="/admin/campaigns">← 목록</a><CampaignStatusActions id={row.id} status={row.status}/></div><div className="dashboard-grid"><section className="panel card"><h2>기본 정보</h2><dl><dt>광고주</dt><dd>{row.company??"-"}</dd><dt>캠페인 코드</dt><dd>{row.code}</dd><dt>랜딩 슬러그</dt><dd>{row.slug}</dd><dt>카테고리</dt><dd>{row.category??"-"}</dd><dt>설명</dt><dd>{row.description??"-"}</dd><dt>등록일</dt><dd>{row.createdAt.toLocaleString("ko-KR")}</dd></dl></section><section className="panel card"><h2>운영 조건</h2><dl><dt>시작</dt><dd>{date(row.startAt)}</dd><dt>종료</dt><dd>{date(row.endAt)}</dd><dt>일 DB 한도</dt><dd>{row.dailyConversionLimit??"제한 없음"}</dd><dt>월 DB 한도</dt><dd>{row.monthlyConversionLimit??"제한 없음"}</dd><dt>일 예산</dt><dd>{row.dailyBudgetLimit?won(row.dailyBudgetLimit):"제한 없음"}</dd><dt>월 예산</dt><dd>{row.monthlyBudgetLimit?won(row.monthlyBudgetLimit):"제한 없음"}</dd><dt>중복 판정</dt><dd>{row.duplicateDays}일</dd><dt>검수 기간</dt><dd>{row.reviewDays}일</dd></dl></section><section className="panel card"><h2>현재 단가</h2>{rate?<dl><dt>광고주 단가</dt><dd>{won(rate.advertiserRate)}</dd><dt>파트너 지급</dt><dd>{won(rate.partnerBaseRate)}</dd><dt>최소 마진</dt><dd>{won(rate.minimumMargin)}</dd><dt>적용일</dt><dd>{rate.effectiveFrom.toLocaleString("ko-KR")}</dd></dl>:<p className="muted">등록된 단가가 없습니다.</p>}</section></div></DashboardShell>}
