import Link from 'next/link';
import type {CSSProperties} from 'react';
import './cpa-guide.css';
export const metadata={title:'CPA 알바란? 참여·승인·수익 가이드 | 마이픽업',description:'CPA 캠페인 선택부터 전용 홍보 링크, 성과 검수와 승인 수익까지. 처음 시작하는 파트너를 위한 마이픽업 이용 안내.',alternates:{canonical:'/about/cpa'}};
function Icon({name}:{name:string}){const paths:Record<string,React.ReactNode>={target:<><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><path d="m12 12 8-8M16 4h4v4"/></>,link:<><path d="m10 13 4-4M8 15l-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m2 3 1-1a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0"/></>,megaphone:<><path d="M4 10v5h4l11 4V5L8 10H4Zm4 5 2 6h4l-2-5M22 9v6"/></>,check:<><path d="m8 12 3 3 5-6"/><path d="m12 2 8 3v6c0 5-4 9-8 11-4-2-8-6-8-11V5Z"/></>,wallet:<><rect x="3" y="5" width="18" height="15" rx="3"/><path d="M3 8h18m0 4h-6v5h6M5 5V3h12"/><path d="M17 14.5h.01"/></>,copy:<><rect x="8" y="8" width="12" height="13" rx="2"/><path d="M15 8V3H3v13h5"/></>,pin:<><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 0 1 14 0Z"/><circle cx="12" cy="10" r="2"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></>,globe:<><circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/></>,alert:<><path d="m12 3 10 18H2Z"/><path d="M12 9v5m0 3h.01"/></>,arrow:<path d="M4 12h16m-6-6 6 6-6 6"/>,list:<><rect x="4" y="3" width="16" height="18" rx="3"/><path d="M8 8h8m-8 4h8m-8 4h5"/></>};return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]??paths.check}</svg>}
const steps=[['target','캠페인 고르기','건당 수익과 대상 지역, 모집 기간을 비교해 나에게 맞는 캠페인을 선택하세요.'],['link','내 링크 발급하기','상세 조건을 확인한 뒤 본인에게 연결되는 전용 홍보 링크를 발급받으세요.'],['megaphone','허용된 매체에 홍보','캠페인에서 허용한 채널과 표현을 사용해 실제 고객에게 정보를 전달하세요.'],['check','성과 접수와 검수','상담·신청이 접수되면 중복 여부와 인정 조건에 따라 검수가 진행됩니다.'],['wallet','승인 수익 확인','최종 승인된 성과의 수익을 확인하고, 출금 가능한 금액을 살펴보세요.']];
const checks=[['wallet','건당 수익','성과 1건이 승인됐을 때 반영되는 파트너 수익'],['copy','중복 기준','동일 고객의 재신청 인정 기간과 조건'],['pin','대상 지역','실제로 서비스를 제공하고 성과를 인정하는 지역'],['clock','운영 시간','상담 접수와 유효 성과로 인정되는 시간'],['globe','허용 매체','사용할 수 있는 검색·SNS·커뮤니티 등 홍보 채널'],['alert','금지 사항','금지 키워드, 과장 표현과 허용되지 않은 홍보 방식']];
const faq=[['링크 클릭만으로 수익이 생기나요?','클릭만으로는 수익이 확정되지 않습니다. 캠페인이 정한 상담·신청 등 목표 행동이 발생하고 최종 승인을 받아야 수익에 반영됩니다.'],['처음 가입하면 바로 참여할 수 있나요?','캠페인 목록은 가입 전에도 볼 수 있습니다. 링크 발급과 참여는 파트너 가입 신청 후 관리자 승인을 받은 계정으로 진행합니다.'],['접수된 성과가 반려되는 이유는 무엇인가요?','중복 신청, 대상 지역·조건 불일치, 잘못된 정보 등이 캠페인별 반려 기준에 해당할 수 있습니다. 내 전환 내역에서 상태를 확인하세요.'],['어느 채널에나 홍보해도 되나요?','캠페인마다 허용 매체가 다릅니다. 상세페이지에서 홍보 가능한 채널과 금지사항을 먼저 확인해 주세요.'],['승인 후 수익은 어디에서 확인하나요?','수익확인 화면에서 반영된 금액을 확인할 수 있습니다. 출금 신청 전에는 출금 가능한 금액과 신청 조건을 함께 확인하세요.']];
export default function Page(){return <main className="cpa-refresh">
<nav className="cr-subnav" aria-label="이용 안내"><div className="container"><Link href="/about">초보자 가이드</Link><Link href="/about/cpa" aria-current="page">CPA 알바</Link><Link href="/about/posting">포스팅 알바</Link><Link href="/about/advertiser">광고주 가이드</Link></div></nav>
<section className="cr-hero"><div className="container cr-hero-grid"><div className="cr-hero-copy"><span className="cr-eyebrow"><span/>처음 시작하는 CPA 가이드</span><h1>좋은 정보를 연결하고,<br/><em>승인된 성과로 수익을.</em></h1><p>내 전용 링크로 캠페인을 알리고,<br className="cr-desktop-break"/> 상담·신청이 승인되면 수익이 반영됩니다.<br/>처음이라면 아래 순서부터 확인해 보세요.</p><div className="cr-actions"><Link className="cr-button primary" href="/partner/campaigns">캠페인 둘러보기<Icon name="arrow"/></Link><a className="cr-button secondary" href="#how-to">참여 방법 보기</a></div><small>참여는 파트너 가입 신청 후 관리자 승인이 필요합니다.</small></div><div className="cr-visual" aria-label="CPA 흐름: 내 링크로 홍보, 상담 또는 신청 접수, 검수 승인 후 수익 반영"><div className="cr-visual-top"><span>MY PICKUP</span><span className="cr-demo-tag">이용 흐름 예시</span></div><div className="cr-orbit"><span className="cr-orbit-icon"><Icon name="target"/></span><b>연결이 성과가 되는 순간</b><p>홍보부터 승인까지, 한 단계씩</p></div><div className="cr-mini-flow">{[['link','내 링크로 홍보'],['list','상담·신청 접수'],['wallet','검수 승인 → 수익']].map((x,i)=><div key={x[0]} style={{'--i':i} as CSSProperties}><span><Icon name={x[0]}/></span><b>{x[1]}</b><span className="cr-mini-index">0{i+1}</span></div>)}</div><p className="cr-visual-note"><Icon name="check"/>클릭 수가 아닌, 승인된 성과가 기준입니다.</p></div></div></section>
<section className="container cr-intro cr-section"><div><span className="cr-kicker">01 · 핵심 이해</span><h2>CPA, 이렇게 생각하면 쉬워요.</h2></div><p>가게를 소개해 실제 상담으로 이어지도록 연결하는 역할과 비슷합니다. <strong>링크 클릭 → 상담·신청 → 검수 → 승인</strong>을 거친 성과가 수익이 됩니다.</p><div className="cr-example"><Icon name="megaphone"/><div><b>예를 들어 이사 상담 캠페인이라면</b><p>내 링크로 고객이 상담을 신청하고, 지역·중복 등 인정 조건을 충족해 승인됐을 때 해당 성과의 수익이 반영됩니다.</p></div></div></section>
<section className="cr-tinted" id="how-to"><div className="container cr-section"><div className="cr-section-head"><div><span className="cr-kicker">02 · 참여 순서</span><h2>첫 참여는 이 다섯 단계로.</h2></div><p>조건 확인부터 수익 확인까지<br/>순서대로 따라가세요.</p></div><ol className="cr-steps">{steps.map((s,i)=><li key={s[0]}><span className="cr-step-number">STEP 0{i+1}</span><span className="cr-icon"><Icon name={s[0]}/></span><h3>{s[1]}</h3><p>{s[2]}</p></li>)}</ol><div className="cr-shortcuts"><div><b>참여 후에는 여기에서 확인하세요.</b><p>내 링크, 접수 내역, 승인 수익을 각각 확인할 수 있어요.</p></div><div><Link href="/partner/links">내 홍보 링크<Icon name="arrow"/></Link><Link href="/partner/conversions">내 전환 내역<Icon name="arrow"/></Link><Link href="/partner/earnings">수익확인<Icon name="arrow"/></Link></div></div></div></section>
<section className="container cr-section"><span className="cr-kicker">03 · 참여 전 체크</span><h2>단가와 함께, 조건도 확인하세요.</h2><p className="cr-section-lead">높은 단가보다 내가 충족할 수 있는 참여 조건이 먼저입니다.</p><div className="cr-checks">{checks.map(x=><article key={x[0]}><span className="cr-icon"><Icon name={x[0]}/></span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></section>
<section className="cr-status-section"><div className="container cr-section"><div className="cr-section-head"><div><span className="cr-kicker">04 · 결과 확인</span><h2>접수와 승인은 다른 단계예요.</h2></div><p>접수 직후에는 수익이 확정되지 않습니다.<br/>검수 결과를 확인해 주세요.</p></div><div className="cr-status-grid">{[['list','접수','성과 정보가 정상적으로 들어온 상태'],['clock','검수중','유효 여부와 인정 조건을 확인하는 상태'],['check','승인','조건을 충족해 수익이 반영되는 상태'],['alert','반려','중복·조건 불충족 등으로 인정되지 않은 상태']].map((x,i)=><article key={x[1]} className={'cr-state-'+i}><Icon name={x[0]}/><span>{x[1]}</span><p>{x[2]}</p></article>)}</div><aside className="cr-warning"><Icon name="alert"/><div><h3>정확한 정보로 홍보해 주세요.</h3><p>허위·과장 표현, 금지 키워드, 허용되지 않은 매체와 허위 신청은 반려 사유가 될 수 있습니다. 캠페인의 승인·반려 기준을 먼저 확인하세요.</p></div></aside></div></section>
<section className="container cr-section cr-faq"><div><span className="cr-kicker">05 · 자주 묻는 질문</span><h2>시작 전,<br/>궁금한 것부터.</h2><p>추가로 궁금한 점은<br/><Link href="/customer/qna/write">1:1 문의로 알려주세요 →</Link></p></div><div>{faq.map((x,i)=><details key={x[0]} open={i===0}><summary>{x[0]}<span aria-hidden="true">+</span></summary><p>{x[1]}</p></details>)}</div></section>
<section className="container cr-end"><span className="cr-icon"><Icon name="target"/></span><h2>나에게 맞는 캠페인부터 찾아보세요.</h2><p>목록은 먼저 둘러보고, 참여 조건을 충분히 확인하세요.</p><div className="cr-actions"><Link className="cr-button primary" href="/partner/campaigns">CPA 캠페인 보기<Icon name="arrow"/></Link><Link className="cr-button secondary" href="/partner/signup">파트너 가입 신청</Link></div></section>
</main>}
