import Link from 'next/link';
import Image from 'next/image';
import './cpa/cpa-guide.css';
import './beginner-guide.css';
export const metadata={title:'초보자 이용 가이드 | 마이픽업',description:'파트너 회원가입과 로그인, CPA·포스팅·1초알바 선택, 작업 제출과 수익·출금 확인까지. 처음 시작하는 마이픽업 이용 안내.',alternates:{canonical:'/about'}};
function Icon({name}:{name:string}){const paths:Record<string,React.ReactNode>={target:<><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><path d="m12 12 8-8M16 4h4v4"/></>,link:<><path d="m10 13 4-4M8 15l-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m2 3 1-1a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0"/></>,megaphone:<><path d="M4 10v5h4l11 4V5L8 10H4Zm4 5 2 6h4l-2-5M22 9v6"/></>,check:<><path d="m8 12 3 3 5-6"/><path d="m12 2 8 3v6c0 5-4 9-8 11-4-2-8-6-8-11V5Z"/></>,wallet:<><rect x="3" y="5" width="18" height="15" rx="3"/><path d="M3 8h18m0 4h-6v5h6M5 5V3h12"/><path d="M17 14.5h.01"/></>,copy:<><rect x="8" y="8" width="12" height="13" rx="2"/><path d="M15 8V3H3v13h5"/></>,pin:<><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 0 1 14 0Z"/><circle cx="12" cy="10" r="2"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></>,globe:<><circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/></>,alert:<><path d="m12 3 10 18H2Z"/><path d="M12 9v5m0 3h.01"/></>,arrow:<path d="M4 12h16m-6-6 6 6-6 6"/>,list:<><rect x="4" y="3" width="16" height="18" rx="3"/><path d="M8 8h8m-8 4h8m-8 4h5"/></>};return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]??paths.check}</svg>}
const steps=[
{no:'01',icon:'list',title:'회원가입하고 바로 시작해요.',desc:'파트너는 별도 승인 없이 가입 즉시 이용할 수 있습니다. 가입이 완료되면 자동 로그인되어 마이페이지로 이동합니다.',points:['회원가입 → 자동 로그인 → 광고 참여','광고 목록은 가입 전에도 둘러볼 수 있어요.','이후에는 가입한 이메일과 비밀번호로 로그인하세요.'],href:'/partner/signup',action:'파트너 회원가입',image:'가입 신청·로그인 화면',caption:'가입 신청 항목과 로그인 위치를 보여줄 화면 이미지'},
{no:'02',icon:'target',title:'내가 할 수 있는 작업을 골라요.',desc:'홍보가 편하다면 CPA, 글 작성이 익숙하다면 포스팅을 살펴보세요. 1초알바도 작업별 조건과 증빙 요구사항을 확인해야 합니다.',points:['CPA: 상담·신청 등 성과가 승인되면 수익 반영','포스팅: 직접 작성한 게시물의 검수 승인 기준','1초알바: 지정된 작업과 증빙 제출·검수 기준'],href:'/partner/campaigns',action:'CPA 캠페인 둘러보기',image:'광고 목록·조건 비교 화면',caption:'단가, 기간과 참여 조건의 위치를 보여줄 화면 이미지'},
{no:'03',icon:'megaphone',title:'조건을 확인하고, 참여·제출해요.',desc:'작업을 시작하기 전에 상세 가이드와 금지사항을 확인하세요. 유형에 따라 참여와 제출 방식이 다릅니다.',points:['CPA: 내 전용 링크를 발급받아 허용된 매체에 홍보','포스팅: 신청 → 작성·게시 → 내 포스팅에서 URL 제출','1초알바: 작업 상세 안내에 맞춰 수행하고 증빙 제출'],href:'/partner/posting/my',action:'내 포스팅 확인',image:'캠페인 상세·제출 화면',caption:'참여 조건과 링크 발급·결과 제출 위치를 보여줄 화면 이미지'},
{no:'04',icon:'check',title:'검수 결과와 수익을 확인해요.',desc:'참여하거나 제출했다고 바로 수익이 확정되지는 않아요. 승인·수정 요청·반려 결과를 확인하고 필요한 후속 작업을 진행하세요.',points:['CPA 접수 결과: 내 전환 내역','포스팅·1초알바: 각 유형의 내 작업 화면','승인 후 반영된 금액: 수익확인'],href:'/partner/earnings',action:'수익확인',image:'내 활동·검수 결과 화면',caption:'진행 상태와 승인 수익을 확인할 위치를 보여줄 화면 이미지'},
{no:'05',icon:'wallet',title:'출금 가능 금액을 보고 신청해요.',desc:'수익확인과 출금신청은 서로 다른 화면이에요. 출금 가능한 금액과 신청 조건, 필요한 정보를 확인한 뒤 신청하세요.',points:['출금 가능한 금액과 신청 조건 확인','필요한 출금 정보 확인 후 신청','신청 내역에서 처리 상태 확인'],href:'/partner/settlements',action:'출금신청 확인',image:'출금 신청·처리 내역 화면',caption:'출금 가능 금액과 신청 내역 위치를 보여줄 화면 이미지'}];
const terms=[["CPA","상담·신청 등 캠페인이 정한 성과가 승인될 때 수익이 발생하는 방식"],["캠페인","광고주가 참여 조건, 단가, 기간과 승인 기준을 정해 등록한 광고"],["전환","광고를 통해 상담·신청 등 목표 행동이 발생한 건"],["승인","광고주의 인정 기준을 충족해 수익 대상으로 확정된 상태"],["포스팅","블로그·카페·SNS 등에 가이드에 맞는 콘텐츠를 작성하는 활동"],["검수","접수된 성과나 게시물이 캠페인 조건을 충족했는지 확인하는 과정"],["정산","승인되어 지급 가능한 수익을 신청하고 지급받는 과정"],["중복 기준","동일 고객의 반복 신청을 인정하는지 판단하는 캠페인별 조건"]];
const faqs=[["CPA와 포스팅 알바 중 무엇부터 해야 하나요?","운영하는 채널과 활동 방식에 맞춰 선택하면 됩니다. 콘텐츠 작성이 익숙하면 포스팅, 고객 유입과 성과형 홍보에 익숙하면 CPA부터 살펴보세요."],["캠페인마다 수익이 다른 이유는 무엇인가요?","광고 유형, 인정 조건, 난이도와 광고주가 설정한 단가가 다르기 때문입니다."],["참여하면 모든 건이 바로 수익으로 인정되나요?","아닙니다. 각 캠페인의 승인 기준에 따라 검수 후 승인된 건이 수익에 반영됩니다."],["포스팅은 아무 글이나 작성해도 되나요?","캠페인별 최소 글자 수, 이미지 수, 유지기간, 필수 내용과 금지사항을 따라야 합니다."],["성과가 반려되면 어떻게 확인하나요?","내 활동의 진행상태와 캠페인별 검수 결과를 확인해 주세요."],["정산 전 무엇을 확인해야 하나요?","정산 가능 수익, 신청 조건과 필요한 회원 정보를 먼저 확인해 주세요."]];
function ImageSlot({title,caption,hero=false,imageNo=1}:{title:string;caption:string;hero?:boolean;imageNo?:number}){return <figure className={'br-image-slot'+(hero?' br-image-hero':'')}><div className="br-guide-image"><Image src={`/images/guide/mypickup-guide-${String(imageNo).padStart(2,'0')}.webp`} alt={title} width={hero?1448:1536} height={hero?1086:1024} sizes="(max-width: 760px) 100vw, 50vw" priority={hero}/></div><figcaption><b>{title}</b><p>{caption}</p></figcaption></figure>}
export default function Page(){return <main className="cpa-refresh beginner-refresh">
<nav className="cr-subnav" aria-label="이용 안내"><div className="container"><Link href="/about" aria-current="page">초보자 가이드</Link><Link href="/about/cpa">CPA 알바</Link><Link href="/about/posting">포스팅 알바</Link><Link href="/about/advertiser">광고주 가이드</Link></div></nav>
<section className="cr-hero"><div className="container cr-hero-grid"><div className="cr-hero-copy"><span className="cr-eyebrow"><span/>마이픽업 첫걸음</span><h1>처음이라도 괜찮아요.<br/><em>한 단계씩 시작해 보세요.</em></h1><p>회원가입부터 첫 참여, 수익 확인까지.<br/>어디를 누르고 무엇을 확인해야 하는지<br/>이 가이드에서 차근차근 알아보세요.</p><div className="cr-actions"><a className="cr-button primary" href="#step-01">첫 단계부터 보기<Icon name="arrow"/></a><Link className="cr-button secondary" href="/partner/signup">파트너 회원가입</Link></div><small>참여 전에는 캠페인별 조건과 검수 기준을 꼭 확인해 주세요.</small></div><ImageSlot hero title="마이픽업 첫 화면 안내" caption="주요 메뉴와 내 활동·수익확인 위치를 보여줄 화면 이미지"/></div></section>
<nav className="container br-step-jump" aria-label="단계 바로가기">{steps.map(s=><a key={s.no} href={'#step-'+s.no}><span>{s.no}</span><Icon name={s.icon}/><b>{['가입·로그인','유형 선택','참여·제출','검수·수익','출금신청'][Number(s.no)-1]}</b></a>)}</nav>
<section className="container cr-section"><span className="cr-kicker">나에게 맞는 시작</span><h2>어떤 작업이 나와 잘 맞을까요?</h2><p className="cr-section-lead">이름보다 실제 작업 방식과 인정 조건을 먼저 살펴보세요.</p><div className="br-types">{[['link','CPA 알바','홍보로 상담·신청을 연결해요.','전용 링크로 접수된 성과가 검수 승인됐을 때 수익이 반영됩니다.','/about/cpa','CPA 자세히 보기'],['megaphone','포스팅 알바','내 채널에 콘텐츠를 작성해요.','참여 신청 후 작성·게시하고 URL을 제출해 검수받습니다.','/about/posting','포스팅 자세히 보기'],['clock','1초알바','작업별 미션을 수행해요.','작업 조건과 필요한 증빙을 확인하고 결과를 제출해 검수받습니다.','/partner/quick','1초알바 목록 보기']].map(x=><article key={x[1]}><span className="cr-icon"><Icon name={x[0]}/></span><span className="br-type-label">{x[1]}</span><h3>{x[2]}</h3><p>{x[3]}</p><Link href={x[4]}>{x[5]}<Icon name="arrow"/></Link></article>)}</div></section>
<section className="br-step-sections" aria-label="시작부터 출금까지">{steps.map((s,i)=><section className={i%2?'br-step alt':'br-step'} id={'step-'+s.no} key={s.no}><div className="container br-step-grid"><div className="br-step-copy"><div className="br-step-label"><span className="cr-icon"><Icon name={s.icon}/></span><span>STEP {s.no}</span></div><h2>{s.title}</h2><p>{s.desc}</p><ul>{s.points.map(x=><li key={x}><Icon name="check"/><span>{x}</span></li>)}</ul><Link className="cr-button secondary" href={s.href}>{s.action}<Icon name="arrow"/></Link></div><ImageSlot title={s.image} caption={s.caption} imageNo={i+2}/></div></section>)}</section>
<section className="container cr-section br-help"><span className="cr-kicker">길을 잃었다면</span><h2>자주 찾는 화면을 바로 열어보세요.</h2><div className="br-help-grid">{[['link','내 홍보 링크','발급한 CPA 링크 확인','/partner/links'],['list','내 전환 내역','CPA 성과 접수·검수 확인','/partner/conversions'],['megaphone','내 포스팅','URL 제출과 수정 요청 확인','/partner/posting/my'],['clock','내 1초알바','참여 작업과 검수 결과 확인','/partner/quick/my'],['wallet','수익확인','승인 후 반영된 수익 확인','/partner/earnings'],['check','출금신청','출금 가능 금액과 신청 내역','/partner/settlements']].map(x=><Link href={x[3]} key={x[1]}><Icon name={x[0]}/><div><b>{x[1]}</b><span>{x[2]}</span></div><Icon name="arrow"/></Link>)}</div><p>내 활동 화면은 파트너 계정으로 로그인한 뒤 이용할 수 있습니다.</p></section>
<section className="br-terms-section"><div className="container cr-section"><span className="cr-kicker">쉬운 용어 사전</span><h2>처음 보는 단어, 이렇게 이해하세요.</h2><div className="br-terms">{terms.map(x=><article key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
<section className="container cr-section cr-faq"><div><span className="cr-kicker">자주 묻는 질문</span><h2>시작하면서<br/>궁금한 것들.</h2><p>안내를 읽어도 헷갈린다면<br/><Link href="/customer/qna/write">1:1 문의로 알려주세요 →</Link></p></div><div>{faqs.map((x,i)=><details key={x[0]} open={i===0}><summary>{x[0]}<span aria-hidden="true">+</span></summary><p>{x[1]}</p></details>)}</div></section>
<section className="container cr-end"><span className="cr-icon"><Icon name="target"/></span><h2>조건을 확인했다면, 첫 작업을 찾아보세요.</h2><p>목록을 둘러보고 내 활동 방식에 맞는 캠페인부터 선택하세요.</p><div className="cr-actions"><Link className="cr-button primary" href="/partner/campaigns">캠페인 둘러보기<Icon name="arrow"/></Link><Link className="cr-button secondary" href="/partner/signup">파트너 회원가입</Link></div></section>
</main>}
