import Link from "next/link";
import "../finance.css";
import DashboardShell from "@/components/DashboardShell";
import { desc, eq, sql } from "drizzle-orm";
import { getDb } from "@/db";
import { requirePartner } from "@/lib/auth/guards";
import { conversions, earnings, postingSubmissions } from "@/db/schema";
export const dynamic="force-dynamic";
const nav=[{href:"/partner",label:"대시보드"},{href:"/partner/conversions",label:"전환 실적"},{href:"/partner/posting/my",label:"내 포스팅"},{href:"/partner/earnings",label:"수익"},{href:"/partner/settlements",label:"정산"}];
const statusLabel:Record<string,string>={AVAILABLE:"출금 가능",HOLD:"출금 처리 중",PAID:"지급 완료",CANCELLED:"취소"};
const formatDate=(value:Date)=>value.toLocaleString("ko-KR",{timeZone:"Asia/Seoul"});
export default async function PartnerEarningsPage({searchParams}:{searchParams:Promise<{status?:string|string[]}>}){const raw=(await searchParams).status;const status=typeof raw==="string"&&(raw==="ALL"||Object.hasOwn(statusLabel,raw))?raw:"ALL";const user=await requirePartner(),db=getDb();const[summary]=await db.select({total:sql<number>`coalesce(sum(case when ${earnings.status}<>'CANCELLED' then ${earnings.amount} else 0 end),0)::int`,available:sql<number>`coalesce(sum(case when ${earnings.status}='AVAILABLE' then ${earnings.amount} else 0 end),0)::int`,hold:sql<number>`coalesce(sum(case when ${earnings.status}='HOLD' then ${earnings.amount} else 0 end),0)::int`,paid:sql<number>`coalesce(sum(case when ${earnings.status}='PAID' then ${earnings.amount} else 0 end),0)::int`,posting:sql<number>`coalesce(sum(case when ${earnings.postingSubmissionId} is not null then ${earnings.amount} else 0 end),0)::int`}).from(earnings).where(eq(earnings.partnerId,user.partnerId!));const rows=await db.select({id:earnings.id,amount:earnings.amount,status:earnings.status,type:earnings.type,description:earnings.description,createdAt:earnings.createdAt,conversionCode:conversions.conversionCode,postingId:postingSubmissions.id,postingTitle:postingSubmissions.title,postUrl:postingSubmissions.postUrl}).from(earnings).leftJoin(conversions,eq(earnings.conversionId,conversions.id)).leftJoin(postingSubmissions,eq(earnings.postingSubmissionId,postingSubmissions.id)).where(eq(earnings.partnerId,user.partnerId!)).orderBy(desc(earnings.createdAt));const filtered=rows.filter(r=>status==='ALL'||r.status===status);
return <DashboardShell title="수익" nav={nav}><div className="partner-finance">
<header className="pf-head"><div><h1>내 수익</h1><p>승인된 CPA·포스팅·1초알바 수익을 확인하세요.</p></div><Link href="/partner/settlements#request" className="pf-primary">출금 신청하기 →</Link></header>
<section className="pf-stats" aria-label="수익 현황">{[
['출금 가능',summary?.available,'지금 신청할 수 있는 확정 수익','featured'],['출금 처리 중',summary?.hold,'신청 후 검토·지급을 기다리는 금액',''],['지급 완료',summary?.paid,'지급이 완료된 수익',''],['누적 확정 수익',summary?.total,'취소된 수익을 제외한 누적 금액','']
].map(([label,amount,help,cls])=><div className={'pf-stat '+cls} key={String(label)}><span>{label}</span><strong>{Number(amount??0).toLocaleString('ko-KR')}원</strong><small>{help}</small></div>)}</section>
<p className="pf-help">작업 검수 중인 보상은 아직 확정 수익에 포함되지 않습니다. 승인 후 이 화면에 반영됩니다.</p>
<section className="pf-panel"><div className="pf-section-head"><div><h2>수익 내역</h2><p>작업 종류와 출금 상태를 확인하세요.</p></div><span>{filtered.length.toLocaleString('ko-KR')}건</span></div>
<nav className="pf-filters" aria-label="수익 상태 필터">{Object.entries({ALL:'전체',...statusLabel}).map(([key,label])=><Link href={'/partner/earnings?status='+key} key={key} aria-current={status===key?'page':undefined}>{label}</Link>)}</nav>
{filtered.length?filtered.map(r=><article className="pf-record" key={r.id}><div><span className="pf-badge">{r.type==='QUICK_APPROVAL'?'1초알바':r.postingId?'포스팅':'CPA'}</span><h3>{r.description||r.postingTitle||'확정 수익'}</h3><time dateTime={r.createdAt.toISOString()}>{formatDate(r.createdAt)}</time><p>{r.type==='QUICK_APPROVAL'?<Link href="/partner/quick/my">제출내역 보기 →</Link>:r.postingId?<Link href="/partner/posting/my">포스팅 내역 보기 →</Link>:r.conversionCode||'전환 승인 수익'}</p></div><div className="pf-amount"><strong>{r.amount.toLocaleString('ko-KR')}원</strong><span className={'pf-badge '+r.status}>{statusLabel[r.status]??r.status}</span></div></article>):<div className="pf-empty">{rows.length?'선택한 상태의 수익이 없습니다.':'아직 확정된 수익이 없습니다. 작업 승인 후 여기에 표시됩니다.'}<br/><Link href="/partner/quick">참여할 작업 보기 →</Link></div>}
</section></div></DashboardShell>}
