import Link from 'next/link';
import '../cpa/cpa-guide.css';
import './advertiser-guide.css';
export const metadata={title:'광고주 가이드 | 마이픽업',description:'CPA·포스팅 광고 유형 선택부터 운영 상담, 캠페인 등록과 성과 검수까지. 마이픽업 광고주 이용 안내.',alternates:{canonical:'/about/advertiser'}};
function Icon({name}:{name:string}){const paths:Record<string,React.ReactNode>={target:<><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><path d="m12 12 8-8M16 4h4v4"/></>,link:<><path d="m10 13 4-4M8 15l-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m2 3 1-1a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0"/></>,megaphone:<><path d="M4 10v5h4l11 4V5L8 10H4Zm4 5 2 6h4l-2-5M22 9v6"/></>,check:<><path d="m8 12 3 3 5-6"/><path d="m12 2 8 3v6c0 5-4 9-8 11-4-2-8-6-8-11V5Z"/></>,wallet:<><rect x="3" y="5" width="18" height="15" rx="3"/><path d="M3 8h18m0 4h-6v5h6M5 5V3h12"/><path d="M17 14.5h.01"/></>,copy:<><rect x="8" y="8" width="12" height="13" rx="2"/><path d="M15 8V3H3v13h5"/></>,pin:<><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 0 1 14 0Z"/><circle cx="12" cy="10" r="2"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></>,globe:<><circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/></>,alert:<><path d="m12 3 10 18H2Z"/><path d="M12 9v5m0 3h.01"/></>,arrow:<path d="M4 12h16m-6-6 6 6-6 6"/>,list:<><rect x="4" y="3" width="16" height="18" rx="3"/><path d="M8 8h8m-8 4h8m-8 4h5"/></>};return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]??paths.check}</svg>}
const steps=[['target','광고 목표 정하기','상담·견적·신청 또는 콘텐츠 제작 등 원하는 결과와 타깃을 정하세요.'],['list','상담·등록 요청','광고 유형, 기간, 단가와 참여 조건을 정리해 관리자에게 등록을 요청하세요.'],['megaphone','검토 후 운영 시작','등록 내용과 인정 조건을 함께 확인한 뒤 캠페인 운영을 시작합니다.'],['check','성과·콘텐츠 검수','접수된 성과와 제출된 게시물을 캠페인의 승인 기준에 따라 확인하세요.'],['wallet','결과와 비용 확인','광고주 화면에서 승인·반려 내역, 캠페인 상태와 비용을 확인하세요.']];
const checks=[['target','광고 목표','상담·견적·신청·콘텐츠 중 어떤 결과가 필요한가요?'],['pin','운영 범위','대상 지역, 기간, 모집 수량과 참여 조건을 정하세요.'],['wallet','단가와 비용','성과·게시물 단가와 운영 비용을 상담 시 확인하세요.'],['check','인정 기준','승인·반려 조건, 중복 기준과 검수 절차를 정리하세요.'],['globe','홍보 채널','파트너가 사용할 수 있는 매체와 금지 방식을 안내하세요.'],['list','필수 안내','소개 자료, 키워드와 콘텐츠 작성 기준을 준비하세요.']];
const faq=[['광고를 직접 등록할 수 있나요?','광고주 가입 신청 후 관리자 승인을 받아 로그인할 수 있습니다. 캠페인 등록은 관리자가 진행합니다. 광고 운영 문의에 목표와 유형, 운영 조건을 남겨 등록을 요청해 주세요.'],['CPA와 포스팅 중 무엇을 선택해야 하나요?','상담·신청 같은 목표 행동을 중심으로 운영하려면 CPA, 가이드에 맞는 게시물을 제작·검수하려면 포스팅을 살펴보세요. 실제 운영 방식은 상담에서 확인할 수 있습니다.'],['접수된 성과는 모두 승인해야 하나요?','캠페인에서 정한 인정 기준으로 검수합니다. 중복, 대상 조건 불일치 등 반려 기준에 해당하는 건은 검수 결과에 따라 처리합니다.'],['기존 광고주는 어디에서 확인하나요?','광고주 계정으로 로그인하면 캠페인, 전환·포스팅 검수 내역과 비용을 확인할 수 있습니다.'],['처음 문의할 때 무엇을 보내면 되나요?','사업·서비스 소개와 광고 목표, 대상 지역, 희망 기간, 운영 수량과 인정 기준을 함께 정리하면 상담에 도움이 됩니다.']];
export default function Page(){return <main className="cpa-refresh advertiser-refresh">
<nav className="cr-subnav" aria-label="이용 안내"><div className="container"><Link href="/about">초보자 가이드</Link><Link href="/about/cpa">CPA 알바</Link><Link href="/about/posting">포스팅 알바</Link><Link href="/about/advertiser" aria-current="page">광고주 가이드</Link></div></nav>
<section className="cr-hero"><div className="container cr-hero-grid"><div className="cr-hero-copy"><span className="cr-eyebrow"><span/>브랜드를 위한 광고 운영 가이드</span><h1>광고의 목표를 정하고,<br/><em>성과를 함께 확인하세요.</em></h1><p>상담·신청을 연결하는 CPA부터<br/>콘텐츠를 제작하는 포스팅까지.<br/>내 비즈니스에 맞는 캠페인을 준비하세요.</p><div className="cr-actions"><Link className="cr-button primary" href="/advertiser/signup">광고주 가입 신청<Icon name="arrow"/></Link><a className="cr-button secondary" href="#advertiser-process">운영 절차 보기</a></div><small>광고주는 가입 신청 후 관리자 승인을 받아 이용합니다. 캠페인 등록은 운영 상담 후 관리자가 진행합니다.</small></div>
<div className="ar-board" aria-label="광고 운영 흐름 예시"><div className="ar-board-head"><span>CAMPAIGN WORKSPACE</span><span>운영 흐름 예시</span></div><div className="ar-board-title"><span className="cr-icon"><Icon name="target"/></span><div><b>목표에서 시작하는 캠페인</b><p>유형 선택 · 조건 설정 · 결과 확인</p></div></div><div className="ar-board-models"><div><Icon name="link"/><b>CPA</b><p>상담·신청 등 목표 성과</p></div><div><Icon name="megaphone"/><b>POSTING</b><p>가이드에 맞는 콘텐츠</p></div></div><div className="ar-board-route">{[['list','운영 조건 준비'],['check','성과·콘텐츠 검수'],['wallet','결과와 비용 확인']].map((x,i)=><div key={x[0]}><span>0{i+1}</span><Icon name={x[0]}/><b>{x[1]}</b></div>)}</div><p className="ar-board-note">실제 운영 현황이나 성과 수치가 아닌 이용 흐름 안내입니다.</p></div></div></section>
<section className="container cr-section"><span className="cr-kicker">01 · 광고 유형 선택</span><h2>어떤 결과가 필요한가요?</h2><p className="cr-section-lead">목표 행동을 연결할지, 콘텐츠를 제작할지 먼저 선택하세요.</p><div className="ar-model-grid"><article><span className="cr-icon"><Icon name="link"/></span><span className="ar-model-label">CPA · 성과형 광고</span><h3>상담과 신청을 연결하고 싶다면.</h3><p>파트너의 전용 링크를 통해 목표 행동이 접수되면, 미리 정한 조건에 따라 유효 성과인지 검수합니다.</p><ul><li>광고 목표: 상담·견적·신청 등</li><li>확인 기준: 지역·중복·인정 조건</li></ul><Link href="/about/cpa">CPA 방식 알아보기<Icon name="arrow"/></Link></article><article><span className="cr-icon"><Icon name="megaphone"/></span><span className="ar-model-label">POSTING · 콘텐츠 광고</span><h3>브랜드를 소개할 콘텐츠가 필요하다면.</h3><p>블로그·카페·SNS 등 지정 매체에 작성된 게시물을 제출받고, 캠페인의 작성 기준에 따라 검수합니다.</p><ul><li>광고 목표: 가이드에 맞는 게시물</li><li>확인 기준: 키워드·분량·유지 기간</li></ul><Link href="/about/posting">포스팅 방식 알아보기<Icon name="arrow"/></Link></article></div></section>
<section className="cr-tinted" id="advertiser-process"><div className="container cr-section"><div className="cr-section-head"><div><span className="cr-kicker">02 · 운영 절차</span><h2>첫 캠페인, 이 순서로 준비하세요.</h2></div><p>상담부터 결과 확인까지<br/>운영 흐름을 미리 살펴보세요.</p></div><ol className="cr-steps">{steps.map((x,i)=><li key={x[1]}><span className="cr-step-number">STEP 0{i+1}</span><span className="cr-icon"><Icon name={x[0]}/></span><h3>{x[1]}</h3><p>{x[2]}</p></li>)}</ol><div className="cr-shortcuts"><div><b>이미 광고주 계정이 있으신가요?</b><p>로그인 후 캠페인과 검수 내역, 비용을 확인하세요.</p></div><div><Link href="/login?next=/advertiser">기존 광고주 로그인<Icon name="arrow"/></Link></div></div></div></section>
<section className="container cr-section"><span className="cr-kicker">03 · 상담 전 준비</span><h2>좋은 캠페인은 명확한 조건에서.</h2><p className="cr-section-lead">아래 여섯 가지를 정리하면 운영 상담이 더 수월해집니다.</p><div className="cr-checks">{checks.map(x=><article key={x[1]}><span className="cr-icon"><Icon name={x[0]}/></span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></section>
<section className="ar-operating"><div className="container cr-section"><div className="cr-section-head"><div><span className="cr-kicker">04 · 운영 중 확인</span><h2>결과와 비용을 함께 살펴보세요.</h2></div><p>접수 수와 승인 결과는 다를 수 있습니다.<br/>정해진 기준에 따라 검수해 주세요.</p></div><div className="ar-operation-grid">{[['target','캠페인 현황','광고 유형과 운영 상태, 참여 조건을 확인합니다.'],['check','검수 결과','접수된 성과와 게시물의 승인·반려 내역을 확인합니다.'],['wallet','운영 비용','비용 내역과 잔액을 확인하고 다음 운영을 준비합니다.']].map(x=><article key={x[1]}><Icon name={x[0]}/><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><aside className="cr-warning"><Icon name="alert"/><div><h3>인정 조건은 운영 전에 공유해 주세요.</h3><p>승인·반려 기준, 허용 매체와 콘텐츠 조건을 명확히 안내하면 파트너가 작업을 준비하기 쉽습니다. 운영 중 조건 변경이 필요하면 관리자와 먼저 확인하세요.</p></div></aside></div></section>
<section className="container cr-section cr-faq"><div><span className="cr-kicker">05 · 자주 묻는 질문</span><h2>광고 시작 전,<br/>궁금한 것부터.</h2><p>구체적인 운영 조건은<br/><Link href="/customer/qna/write">광고 운영 문의로 알려주세요 →</Link></p></div><div>{faq.map((x,i)=><details key={x[0]} open={i===0}><summary>{x[0]}<span aria-hidden="true">+</span></summary><p>{x[1]}</p></details>)}</div></section>
<section className="container cr-end"><span className="cr-icon"><Icon name="target"/></span><h2>다음 캠페인의 목표를 이야기해 주세요.</h2><p>서비스 소개와 원하는 결과를 정리해 운영 상담을 시작하세요.</p><div className="cr-actions"><Link className="cr-button primary" href="/advertiser/signup">광고주 가입 신청<Icon name="arrow"/></Link><Link className="cr-button secondary" href="/login?next=/advertiser">기존 광고주 로그인</Link></div></section>
</main>}
