import Image from "next/image";
import Link from "next/link";
import "./biz-home.css";
import {getDb} from '@/db';
import {campaigns as campaignTable} from '@/db/schema';
import {and,desc,eq,sql} from 'drizzle-orm';
export const dynamic='force-dynamic';
const quickMenus=[
 {label:"CPA알바",href:"/partner/campaigns",icon:"파란 메가폰과 빛나는 음향 파동.png"},
 {label:"포스팅알바",href:"/partner/posting",icon:"광택 3D 문서와 연필 아이콘.png"},
 {label:"1초알바",href:"/partner/quick",icon:"광택 블루 번개 스톱워치 아이콘.png"},
 {label:"수익확인",href:"/partner/earnings",icon:"상승 그래프와 원화 금화 아이콘.png"},
 {label:"고객센터",href:"/customer",icon:"3D 고객지원 챗봇 아바타.png"},
 {label:"광고의뢰(광고주)",href:"/about/advertiser",icon:"계약서와 악수 아이콘.png"}
];
export default async function Home(){let campaigns=null;try{campaigns=await getDb().select({id:campaignTable.id,title:campaignTable.name,kind:campaignTable.category,reward:sql<number|null>`(select r.partner_base_rate from campaign_rates r where r.campaign_id="campaigns"."id" and r.effective_from<=now() and (r.effective_to is null or r.effective_to>now()) order by r.effective_from desc limit 1)`}).from(campaignTable).where(and(eq(campaignTable.type,'CPA'),eq(campaignTable.status,'ACTIVE'),sql`(${campaignTable.startAt} is null or ${campaignTable.startAt}<=now()) and (${campaignTable.endAt} is null or ${campaignTable.endAt}>now())`)).orderBy(desc(campaignTable.createdAt)).limit(5);}catch(error){console.error('Home campaigns failed',error);}return <main className="biz-home">
 <section className="biz-hero"><div className="container biz-hero-grid"><div><span className="biz-pill">성과에 따라 수익이 반영되는 부업 플랫폼</span><h1>지금, 당신의 시간을<br/><b>수익으로 바꿔보세요</b></h1><p>CPA 참여부터 포스팅 알바까지<br/>마이픽업과 함께라면 누구나 쉽게 시작할 수 있습니다.</p><form className="biz-search" action="/partner/campaigns"><input name="q" aria-label="CPA 캠페인 검색" maxLength={160} placeholder="캠페인 이름이나 분야를 검색하세요"/><button aria-label="검색">⌕</button></form><div className="biz-keywords">참여 전 단가와 인정 조건을 확인해 주세요.</div></div><div className="hero-image-slot hero-image-live"><Image src="/images/home/hero-main.png" alt="마이픽업 CPA 및 포스팅 성과형 광고 플랫폼" fill priority sizes="(max-width: 950px) 100vw, 48vw"/></div></div></section>
 <nav className="container category-bar quick-menu-bar">{quickMenus.map((m,i)=><Link key={m.label} href={m.href} className={`quick-menu quick-menu-${i+1}`}><span className="quick-icon"><Image src={`/images/home/menu-icons-numbered/${m.icon}`} alt="" width={96} height={96} className="quick-menu-image" aria-hidden="true"/></span><strong>{m.label}</strong><span className="quick-arrow" aria-hidden="true">›</span></Link>)}</nav>
 <section className="container biz-campaign"><div className="biz-section-head"><div><h2>모집 중인 CPA 캠페인</h2><p>현재 참여 가능한 캠페인의 조건과 승인 수익을 확인하세요.</p></div><Link href="/partner/campaigns">전체 캠페인 보기 →</Link></div><div className="campaign-row">{campaigns?.map((c,i)=><Link href={`/partner/campaigns/${c.id}`} className="biz-card" key={c.id}><span className="state">모집 중</span><div className={`biz-thumb thumb-${i+1}`}><small>{c.kind??'CPA 캠페인'}</small><b>CPA</b></div><h3>{c.title}</h3><p>성과 검수 승인 후 수익 반영</p><strong>{c.reward===null?'단가 확인 필요':`${Number(c.reward).toLocaleString('ko-KR')}원`}</strong></Link>)}</div>{!campaigns?.length&&<p className="home-guide-note">{campaigns===null?'캠페인을 불러오지 못했습니다. 잠시 후 다시 확인해 주세요.':'현재 모집 중인 CPA 캠페인이 없습니다. 포스팅·1초알바에서 다른 작업을 확인해 주세요.'}</p>}</section>
 <section className="biz-service"><div className="container service-grid"><div className="service-intro"><span>ⓘ MYPICKUP SERVICE</span><h2>한 번의 참여로<br/>다양한 브랜드의<br/>캠페인을 만나보세요</h2><p>캠페인의 참여 조건과 검수 결과에 따라 수익을 확인할 수 있습니다.</p><Link className="biz-btn" href="/partner/campaigns">지금 시작하기 →</Link></div><div className="service-cards"><article><b><Image src="/images/home/service-icons/01.png" alt="" width={64} height={64}/></b><div><h3>간편한 참여</h3><p>회원가입 후 캠페인 조건을 확인하고 참여해 주세요.</p></div></article><article><b><Image src="/images/home/service-icons/02.png" alt="" width={64} height={64}/></b><div><h3>다양한 플랫폼</h3><p>캠페인별 허용 매체와 참여 조건을 확인해 주세요.</p></div></article><article><b><Image src="/images/home/service-icons/03.png" alt="" width={64} height={64}/></b><div><h3>안전한 정산</h3><p>검수 승인 수익과 출금 진행 상태를 화면에서 확인할 수 있습니다.</p></div></article><article><b><Image src="/images/home/service-icons/04.png" alt="" width={64} height={64}/></b><div><h3>검수 결과 확인</h3><p>캠페인별 검수 기간과 승인·수정·반려 결과를 확인하세요.</p></div></article></div></div></section>
 <section className="container proof"><h2>가입부터 수익 확인까지</h2><div>{[{no:'01',title:'가입 신청',text:'이메일과 비밀번호로 파트너 가입을 신청합니다.'},{no:'02',title:'바로 시작',text:'가입 즉시 로그인되어 광고에 참여할 수 있습니다.'},{no:'03',title:'참여·검수',text:'조건을 확인하고 작업 또는 성과를 제출합니다.'},{no:'04',title:'수익·출금',text:'승인된 수익을 확인하고 출금을 신청합니다.'}].map(x=><p key={x.no}><b>{x.no}</b><span>{x.title}</span><small>{x.text}</small></p>)}</div></section>
 <section className="container dual-banner"><article className="member-banner"><div><span>초보자도 쉽게</span><h2>지금 바로 수익을<br/>시작해보세요</h2><p>✓ 파트너 가입 즉시 참여 가능<br/>✓ 간단한 미션으로 수익 적립<br/>✓ 친절한 가이드와 1:1 문의 지원</p></div><div className="person-slot member-image"><Image src="/images/home/menu-icons/성공을 향한 핀테크 성장 그래프.png" alt="마이픽업 캠페인 참여 및 수익 성장 이미지" width={560} height={440} priority={false}/></div></article><article className="ad-banner"><div><span>광고주/기업</span><h2>브랜드 성장의<br/>파트너가 되어보세요</h2><p>✓ 캠페인 목표와 인정 조건 설정<br/>✓ 타깃 맞춤형 마케팅 진행<br/>✓ 성과 기반 광고 운영</p></div><div className="person-slot advertiser-image"><Image src="/images/home/menu-icons-numbered/광고 성과 성장 인포그래픽.png" alt="마이픽업 광고주 성과형 광고 성장 인포그래픽" width={560} height={440}/></div></article></section>
 <section className="container join-cta"><div><small>✓ 지금 바로 시작하세요</small><h2>회원가입하고 다양한 캠페인에 참여해보세요</h2><p>모집 목록은 먼저 둘러볼 수 있습니다. 파트너는 가입 즉시 참여할 수 있습니다.</p></div><div><Link href="/partner/signup">파트너 회원가입 →</Link><Link href="/customer/qna/write">1:1 상담 문의</Link></div></section>

 </main>}
