import Link from "next/link";
import "./home-refresh.css";

const categories=[["▦","전체상품"],["▣","보험/금융"],["◆","생활서비스"],["▤","통신/렌탈"],["●","교육/자격"],["✓","설문조사"],["✎","블로그 포스팅"],["★","이벤트"],["↗","API 연동"]];
const campaigns=[
 ["보험·금융","상담 신청 CPA","승인율 확인","건당 수익","/images/home/campaign-01.webp"],
 ["생활서비스","이사·청소·철거 견적","지역 캠페인","건당 수익","/images/home/campaign-02.webp"],
 ["렌탈·통신","렌탈 상담 캠페인","상담 접수","건당 수익","/images/home/campaign-03.webp"],
 ["교육·자격","교육·자격 상담","상담 신청","건당 수익","/images/home/campaign-04.webp"],
 ["콘텐츠","블로그·SNS 포스팅","작업 승인","포스팅 수익","/images/home/campaign-05.webp"]
];
function ImgSlot({src,label,className=""}:{src:string,label:string,className?:string}){return <div className={`mp-image-slot ${className}`} style={{backgroundImage:`url('${src}')`}}><span>{label}<small>{src}</small></span></div>}
export default function HomePage(){return <main className="mp-home">
<section className="mp-hero"><div className="container"><div className="mp-hero-box"><div className="mp-hero-copy"><span className="mp-kicker">성과 온라인 플랫폼 마이픽업</span><h1>지금, 당신의 시간을<br/>수익으로 바꿔보세요</h1><p>CPA 참여부터 포스팅 광고까지<br/>마이픽업과 함께라면 누구나 쉽게 시작할 수 있습니다.</p><div className="mp-search"><span>⌕</span><span className="mp-search-text">원하는 캠페인을 검색해보세요</span><Link href="/campaigns">→</Link></div><div className="mp-keywords"><b>인기검색어</b><span>보험상담</span><span>이사견적</span><span>렌탈상담</span><span>블로그 포스팅</span></div></div><ImgSlot src="/images/home/hero-main.webp" label="메인 비주얼 이미지 영역" className="mp-hero-image"/></div></div></section>
<section className="mp-category"><div className="container mp-category-box">{categories.map(([icon,name])=><Link href="/campaigns" key={name}><i>{icon}</i><b>{name}</b></Link>)}</div></section>
<section className="mp-section"><div className="container"><div className="mp-head"><div><span>MY PICKUP'S PICK!</span><h2>지금 인기 있는 캠페인</h2><p>지금 가장 많이 참여하고 있는 인기 캠페인을 확인해보세요.</p></div><Link href="/campaigns">전체 캠페인 보기 →</Link></div><div className="mp-cards mp-five">{campaigns.map(([cat,title,rate,reward,img],i)=><Link href="/campaigns" className="mp-card" key={title}><div className="mp-campaign-image"><ImgSlot src={img} label={`캠페인 이미지 ${i+1}`}/><span className="mp-status">{i===1?"인기":"진행중"}</span></div><div className="mp-card-body"><small>{cat}</small><h3>{title}</h3><p>{rate}</p><strong>{reward}</strong></div></Link>)}</div></div></section>
<section className="mp-service"><div className="container mp-service-box"><div className="mp-service-intro"><span>MY PICKUP SERVICE</span><h2>한 번의 참여로<br/>다양한 캠페인을<br/>만나보세요</h2><p>검증된 광고주와 함께하는 신뢰할 수 있는 CPA·포스팅 광고 플랫폼입니다.</p><Link className="btn primary" href="/partner">지금 시작하기 →</Link></div><div className="mp-service-cards"><article><i>⌘</i><div><b>간편한 참여</b><p>회원가입 후 원하는 캠페인을 선택하고 바로 참여하세요.</p></div></article><article><i>▣</i><div><b>다양한 캠페인</b><p>생활서비스, 보험, 렌탈, 콘텐츠 등 다양한 캠페인을 제공합니다.</p></div></article><article><i>◇</i><div><b>안전한 정산</b><p>검수된 성과와 투명한 정산 흐름으로 수익을 관리합니다.</p></div></article><article><i>◷</i><div><b>빠른 확인</b><p>대시보드에서 전환과 승인 상태를 편리하게 확인합니다.</p></div></article></div></div></section>
<section className="mp-trust"><div className="container"><h2>마이픽업과 함께 성과를 만들어보세요</h2><div className="mp-numbers"><div><strong>CPA</strong><span>성과형 캠페인</span></div><div><strong>POST</strong><span>포스팅 캠페인</span></div><div><strong>ONE</strong><span>통합 운영·정산</span></div><div><strong>24H</strong><span>온라인 캠페인 확인</span></div></div><div className="mp-dual"><article className="partner"><div><span>파트너</span><h3>지금 바로 수익을<br/>시작해보세요</h3><p>원하는 캠페인을 선택하고 성과를 만들어 수익을 확인하세요.</p><Link href="/partner">파트너 시작하기 →</Link></div><ImgSlot src="/images/home/partner-banner.webp" label="파트너 이미지 영역"/></article><article className="advertiser"><div><span>광고주/기업</span><h3>브랜드 성장의<br/>파트너가 되어보세요</h3><p>성과 기반 광고 운영으로 필요한 고객과 효율적으로 연결하세요.</p><Link href="/advertiser">광고주 시작하기 →</Link></div><ImgSlot src="/images/home/advertiser-banner.webp" label="광고주 이미지 영역"/></article></div><div className="mp-brand-strip"><span>INSURANCE</span><span>LIFE SERVICE</span><span>RENTAL</span><span>EDUCATION</span><span>CONTENT</span><span>PARTNER</span></div><div className="mp-cta"><div><small>지금 바로 시작하세요</small><h2>회원가입하고 다양한 캠페인에 참여해보세요</h2><p>마이픽업에서 광고 성과와 수익을 한곳에서 관리할 수 있습니다.</p></div><div className="actions"><Link className="btn" href="/partner">무료로 시작하기 →</Link><Link className="btn light" href="/customer/qna/write">1:1 상담 문의</Link></div></div></div></section>
<section className="mp-bottom"><div className="container mp-bottom-grid"><div className="mp-notice"><div className="mp-notice-head"><b>공지사항</b><Link href="/customer">더보기 +</Link></div><p>마이픽업 서비스 운영 안내</p><p>CPA 전환 검수 및 승인 기준 안내</p><p>파트너 정산 신청 안내</p></div><div className="mp-support"><span>MY PICKUP CUSTOMER CENTER</span><a href="tel:01026365008">010-2636-5008</a><p>광고주 · 파트너 · 서비스 이용 문의</p></div></div></section><Link className="mp-float" href="/customer/qna/write">M</Link></main>}
