import Link from "next/link";
import "./home-refresh.css";

const cards=[
  ["보험·금융","상담 신청 CPA","승인된 상담 DB를 기준으로 수익이 확정됩니다.","CPA","상담 신청","mp-t1"],
  ["생활서비스","이사·청소·철거 견적","지역별 생활서비스 캠페인을 선택해 참여하세요.","CPA","견적 신청","mp-t2"],
  ["렌탈·통신","렌탈 상담 캠페인","정수기·생활가전 등 상담 접수형 캠페인입니다.","CPA","상담 접수","mp-t3"],
  ["콘텐츠","블로그·SNS 포스팅","콘텐츠 작성 후 검수와 승인을 거쳐 정산합니다.","POST","작업 승인","mp-t4"],
];

export default function HomePage(){return <main className="mp-home">
<section className="mp-hero"><div className="container"><div className="mp-hero-box"><div><span className="mp-kicker">MY PICKUP PERFORMANCE MARKET</span><h1>원하는 광고를 고르고<br/>성과를 픽업하세요.</h1><p>광고주는 필요한 성과를 등록하고 파트너는 원하는 캠페인을 선택합니다.<br/>CPA 전환부터 포스팅 작업과 정산까지 한곳에서 관리하세요.</p><div className="actions"><Link className="btn primary" href="/campaigns">캠페인 둘러보기</Link><Link className="btn light" href="/partner">파트너 시작하기</Link></div></div><div className="mp-console"><div className="mp-console-top"><i/><i/><i/></div><strong>성과가 연결되는 가장 간단한 방법</strong><p>캠페인 선택 → 홍보 → 전환 확인 → 승인 → 정산</p><span className="mp-console-badge">mypickup.kr / performance</span></div></div></div></section>
<section className="mp-quick"><div className="container mp-quick-grid"><Link href="/campaigns"><i>📣</i><b>전체 캠페인</b></Link><Link href="/campaigns"><i>🎯</i><b>CPA 광고</b></Link><Link href="/campaigns"><i>✍️</i><b>포스팅 광고</b></Link><Link href="/partner"><i>🤝</i><b>파트너 센터</b></Link><Link href="/advertiser"><i>📊</i><b>광고주 센터</b></Link><Link href="/customer"><i>💬</i><b>고객센터</b></Link></div></section>
<section className="mp-section"><div className="container"><div className="mp-head"><div><span>MY PICKUP'S PICK</span><h2>지금 참여할 캠페인</h2></div><Link href="/campaigns">전체 캠페인 →</Link></div><div className="mp-filter"><span>추천</span><span>보험·금융</span><span>생활서비스</span><span>렌탈·통신</span><span>콘텐츠</span></div><div className="mp-cards">{cards.map(([cat,title,desc,kind,action,tone])=><Link href="/campaigns" className="mp-card" key={title}><div className={`mp-thumb ${tone}`}><small>{cat}</small><strong>{title}</strong></div><div className="mp-card-body"><em>{kind}</em><h3>{title}</h3><p>{desc}</p><div className="mp-card-meta"><span>성과 조건</span><strong>{action}</strong></div></div></Link>)}</div></div></section>
<section className="mp-benefit"><div className="container mp-benefit-grid"><div className="mp-benefit-intro"><span>WHY MY PICKUP</span><h2>광고 운영에 필요한 흐름을<br/>하나로 연결했습니다.</h2><p>캠페인을 찾는 과정부터 성과 확인, 검수, 수익 집계와 정산까지 각각 흩어진 업무를 마이픽업에서 관리할 수 있습니다.</p></div><div className="mp-bento"><article><b>성과 중심 캠페인</b><p>단순 노출이 아니라 정해진 전환 조건을 기준으로 성과를 관리합니다.</p><strong>01</strong></article><article><b>실시간 진행 현황</b><p>파트너와 광고주가 각자의 대시보드에서 진행 상태를 확인합니다.</p><strong>02</strong></article><article><b>CPA + POST</b><p>전환형 광고와 콘텐츠 포스팅 업무를 하나의 플랫폼에서 운영합니다.</p><strong>03</strong></article><article><b>정산까지 한 번에</b><p>승인된 성과와 파트너 수익을 연결해 정산 흐름을 단순화합니다.</p><strong>04</strong></article></div></div></section>
<section className="mp-trust"><div className="container"><h2>광고주와 파트너가 함께 만드는 성과 플랫폼</h2><div className="mp-numbers"><div><strong>CPA</strong><span>성과형 캠페인</span></div><div><strong>POST</strong><span>콘텐츠 캠페인</span></div><div><strong>ONE</strong><span>통합 운영·정산</span></div></div><div className="mp-cta"><h2>지금 마이픽업을 시작하세요</h2><p>원하는 캠페인을 찾거나 새로운 광고 캠페인을 등록할 수 있습니다.</p><div className="actions" style={{justifyContent:"center"}}><Link className="btn" href="/partner">파트너 시작하기</Link><Link className="btn light" href="/advertiser">광고주 시작하기</Link></div></div></div></section>
<section className="mp-bottom"><div className="container mp-bottom-grid"><div className="mp-notice"><div className="mp-notice-head"><b>공지사항</b><Link href="/customer">더보기 +</Link></div><p>마이픽업 서비스 운영 안내</p><p>CPA 전환 검수 및 승인 기준 안내</p><p>파트너 정산 신청 안내</p><p>광고주 캠페인 등록 안내</p></div><div className="mp-support"><span>MY PICKUP CUSTOMER CENTER</span><a href="tel:01026365008">010-2636-5008</a><p>광고주 · 파트너 · 서비스 이용 문의</p><Link className="btn primary" href="/customer/qna/write">1:1 문의하기</Link></div></div></section><Link className="mp-float" href="/customer/qna/write" aria-label="문의하기">M</Link>
</main>}
