"use client";
import Link from 'next/link';import {type FormEvent,useState} from 'react';import {loginDestination} from '@/lib/auth/destination';
const messages:Record<string,string>={INVALID_CREDENTIALS:'이메일 또는 비밀번호가 올바르지 않습니다.',APPROVAL_PENDING:'광고주 가입 신청이 승인 대기 중입니다. 관리자 승인 후 로그인할 수 있습니다.',ACCOUNT_DISABLED:'현재 사용할 수 없는 계정입니다. 고객센터로 문의해 주세요.',INVALID_INPUT:'이메일과 비밀번호를 확인해 주세요.',LOGIN_FAILED:'로그인을 처리하지 못했습니다. 잠시 후 다시 시도해 주세요.',INVALID_ORIGIN:'화면을 새로고침한 뒤 다시 시도해 주세요.',ORIGIN_CHECK_FAILED:'화면을 새로고침한 뒤 다시 시도해 주세요.'};
export default function LoginForm({next,notice}:{next?:string;notice?:string}){const[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[show,setShow]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(loading)return;const form=new FormData(event.currentTarget);setLoading(true);setMessage('');try{const res=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(form))});const data=await res.json().catch(()=>{throw new Error('응답을 확인하지 못했습니다. 잠시 후 다시 시도해 주세요.');});if(!res.ok||!data.ok){if(data.error==='TOO_MANY_ATTEMPTS')throw new Error(`로그인 시도가 많아 잠시 제한되었습니다. 약 ${Math.max(1,Math.ceil(Number(data.retryAfter||900)/60))}분 후 다시 시도해 주세요.`);throw new Error(messages[data.error]??messages.LOGIN_FAILED);}window.location.assign(loginDestination(next,data.role));}catch(e){setMessage(e instanceof TypeError?'연결이 원활하지 않습니다. 인터넷 연결을 확인한 뒤 다시 시도해 주세요.':e instanceof Error?e.message:messages.LOGIN_FAILED);}finally{setLoading(false);}}
 return <section className="au-card login-card" aria-labelledby="login-title">
 <span className="login-eyebrow">WELCOME BACK</span><h1 id="login-title">다시 만나 반가워요</h1><p className="au-intro">가입한 이메일로 로그인하고<br/>마이픽업의 활동을 이어가세요.</p>
 {notice&&<p className="au-notice" role="status">{notice}</p>}
 <form onSubmit={submit} aria-busy={loading}><fieldset disabled={loading} className="au-fieldset"><div className="au-fields">
 <div className="login-field"><label htmlFor="login-email">이메일</label><div className="login-input"><LoginIcon kind="mail"/><input id="login-email" name="email" type="email" required maxLength={320} autoComplete="username" autoCapitalize="none" spellCheck={false} placeholder="가입한 이메일 주소"/></div></div>
 <div className="login-field"><label htmlFor="login-password">비밀번호</label><div className="login-input"><LoginIcon kind="lock"/><input id="login-password" name="password" type={show?'text':'password'} required autoComplete="current-password" placeholder="비밀번호를 입력해 주세요"/><button className="login-reveal" type="button" aria-label={show?'비밀번호 숨기기':'비밀번호 보기'} aria-controls="login-password" aria-pressed={show} onClick={()=>setShow(!show)}>{show?'숨기기':'보기'}</button></div></div>
 </div><button className="au-primary" type="submit"><span>{loading?'로그인 중…':'로그인'}</span>{!loading&&<LoginIcon kind="arrow"/>}</button></fieldset>{message&&<p className="au-error" role="alert">{message}</p>}</form>
 <p className="login-account-note"><LoginIcon kind="lock"/>파트너 · 광고주 · 관리자 공통 로그인</p>
 <div className="login-join"><p>마이픽업이 처음이신가요?</p><div className="login-join-grid"><Link href="/partner/signup"><LoginIcon kind="person"/><strong>파트너 회원가입</strong><span>가입 후 바로 시작해요</span><span className="login-join-arrow" aria-hidden="true">↗</span></Link><Link href="/advertiser/signup"><LoginIcon kind="building"/><strong>광고주 가입 신청</strong><span>승인 후 이용할 수 있어요</span><span className="login-join-arrow" aria-hidden="true">↗</span></Link></div></div>
 <Link className="au-help" href="/customer">로그인이 어려우신가요? <strong>고객센터 →</strong></Link></section>;
}
function LoginIcon({kind}:{kind:'mail'|'lock'|'arrow'|'person'|'building'}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" focusable="false">{kind==='mail'?<><rect x="3" y="5" width="18" height="14" rx="3"/><path d="m4 7 8 6 8-6"/></>:kind==='lock'?<><rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/></>:kind==='arrow'?<path d="M5 12h14m-6-6 6 6-6 6"/>:kind==='person'?<><circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/></>:<><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 7h1m4 0h1M9 11h1m4 0h1M10 21v-5h4v5"/></>}</svg>}
