"use client";
import {useState,type FormEvent,type ReactNode} from 'react';
import {useRouter} from 'next/navigation';
const errors:Record<string,string>={Unauthorized:'파트너 로그인 후 이용해 주세요.',FORBIDDEN:'현재 계정의 작업만 제출할 수 있습니다.',NOT_FOUND:'작업 정보를 찾을 수 없습니다.',NOT_ACTIVE:'현재 모집 중인 캠페인이 아닙니다.',NOT_STARTED:'아직 참여 시작일이 되지 않았습니다.',ENDED:'모집이 종료되었습니다.',PARTNER_LIMIT:'이 캠페인의 참여 한도에 도달했습니다. 내 포스팅에서 기존 작업을 확인하세요.',PARTICIPANT_LIMIT:'모집 인원이 모두 채워졌습니다.',INVALID_INPUT:'게시물 제목과 URL을 확인해 주세요.',INVALID_URL:'http 또는 https로 시작하는 게시물 주소를 입력해 주세요.',INVALID_DATE:'게시일을 확인해 주세요.',APPLICATION_CLOSED:'참여가 종료된 작업입니다.',SUBMISSION_LOCKED:'이미 처리된 제출입니다. 내 포스팅에서 상태를 확인하세요.',REVISION_LIMIT:'수정 가능 횟수를 모두 사용했습니다.',SUBMISSION_LIMIT:'제출 가능한 작업 수량이 모두 채워졌습니다.',INVALID_ORIGIN:'화면을 새로고침한 뒤 다시 시도해 주세요.',ORIGIN_CHECK_FAILED:'화면을 새로고침한 뒤 다시 시도해 주세요.'};
export default function PostingActionForm({action,label,children}:{action:'apply'|'submit';label:string;children:ReactNode}){
 const router=useRouter(),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const body=new FormData(e.currentTarget);setBusy(true);setMessage('');try{const response=await fetch('/api/partner/posting/'+action,{method:'POST',body});if(!response.ok){const code=(await response.text()).trim();throw new Error(errors[code]??'처리하지 못했습니다. 잠시 후 다시 시도해 주세요.');}if(!response.redirected)throw new Error('접수 결과를 확인하지 못했습니다. 내 포스팅에서 상태를 확인해 주세요.');router.push('/partner/posting/my');router.refresh();}catch(e){setMessage(e instanceof TypeError?'연결이 원활하지 않습니다. 내 포스팅에서 접수 여부를 확인한 뒤 다시 시도해 주세요.':e instanceof Error?e.message:'처리하지 못했습니다. 잠시 후 다시 시도해 주세요.');}finally{setBusy(false);}}
 return <form onSubmit={submit} aria-busy={busy}><fieldset className="pt-fieldset" disabled={busy}>{children}<button className="pt-button" type="submit">{busy?'처리 중…':label}</button></fieldset>{message&&<p className="pt-notice" role="alert">{message}</p>}</form>;
}
