"use client";
import Link from 'next/link';
import {useMemo,useState} from 'react';
export type PostingItem={id:string;name:string;category:string|null;description:string|null;status:string;mediaType:string;partnerRate:number|null;totalSubmissionLimit:number|null;perPartnerLimit:number;endAt:string|null;isOpen:boolean;stateLabel:string};
export default function PostingMarket({items}:{items:PostingItem[]}){
 const [q,setQ]=useState(''),[media,setMedia]=useState('전체'),[sort,setSort]=useState('추천순');
 const mediaTypes=['전체',...Array.from(new Set(items.map(x=>x.mediaType).filter(Boolean)))];
 const rows=useMemo(()=>items.filter(x=>(media==='전체'||x.mediaType===media)&&(!q.trim()||[x.name,x.category,x.description].join(' ').toLowerCase().includes(q.trim().toLowerCase()))).sort((a,b)=>sort==='수익높은순'?(b.partnerRate??0)-(a.partnerRate??0):sort==='추천순'?Number(b.isOpen)-Number(a.isOpen):0),[items,q,media,sort]);
 return <><div className="posting-tools"><div className="posting-search"><input aria-label="포스팅 작업 검색" value={q} onChange={e=>setQ(e.target.value)} placeholder="작업명이나 내용으로 검색"/>{q&&<button type="button" onClick={()=>setQ('')} aria-label="검색어 지우기">×</button>}</div><select aria-label="포스팅 작업 정렬" value={sort} onChange={e=>setSort(e.target.value)}><option>추천순</option><option>최신순</option><option>수익높은순</option></select></div><nav className="posting-media" aria-label="작성 매체 필터">{mediaTypes.map(x=><button type="button" key={x} aria-pressed={media===x} className={media===x?'active':''} onClick={()=>setMedia(x)}>{x}</button>)}</nav><div className="posting-list-head"><b>포스팅 작업</b><span>총 <strong>{rows.length}</strong>개</span></div><div className="pt-cards">{rows.map(x=><article className="pt-job" key={x.id}><div className="pt-job-top"><span className="pt-media">{x.mediaType}</span><span className={'pt-state '+(x.isOpen?'open':'')}>{x.stateLabel}</span></div><h2><Link href={'/partner/posting/'+x.id}>{x.name}</Link></h2><p>{x.description||'상세 작성 조건을 확인한 뒤 참여해 주세요.'}</p><div className="pt-reward"><span>건당 수익</span><strong>{x.partnerRate==null?'단가 확인 중':x.partnerRate.toLocaleString('ko-KR')+'원'}</strong></div><dl><div><dt>1인 작업 한도</dt><dd>{x.perPartnerLimit}건</dd></div><div><dt>모집 종료일</dt><dd>{x.endAt?new Date(x.endAt).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'}):'별도 지정 없음'}</dd></div></dl><Link className="pt-card-link" href={'/partner/posting/'+x.id}>작성 조건 확인 →</Link></article>)}</div>{!rows.length&&<div className="posting-empty">{items.length?'조건에 맞는 작업이 없습니다. 검색어와 매체를 변경해 주세요.':'등록된 포스팅 작업이 없습니다. 새 모집 작업이 등록되면 이곳에 표시됩니다.'}</div>}</>;
}
