"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
export type QuickJob={id:string;title:string;type:string;reward:number;remaining:number;status:"OPEN"|"CLOSED";icon:string;description:string};
const icons:Record<string,string>={앱설치:"↓",채널구독:"▶",영상시청:"▷",페이지방문:"↗",설문:"☑",SNS:"#"};
export default function QuickJobMarket({items}:{items:QuickJob[]}){
 const [q,setQ]=useState("");const [type,setType]=useState("전체");const [sort,setSort]=useState("추천순");
 const types=["전체",...Array.from(new Set(items.map(x=>x.type)))];
 const rows=useMemo(()=>{const query=q.trim().toLowerCase();return items.filter(x=>(type==="전체"||x.type===type)&&(!query||(x.title+" "+x.description+" "+x.type).toLowerCase().includes(query))).sort((a,b)=>sort==="수익높은순"?b.reward-a.reward:sort==="잔여많은순"?b.remaining-a.remaining:Number(b.status==="OPEN")-Number(a.status==="OPEN"));},[items,q,type,sort]);
 return <><section className="qj-tools" aria-label="작업 검색 및 정렬"><div className="qj-search"><span aria-hidden="true">⌕</span><input aria-label="1초알바 검색" value={q} onChange={e=>setQ(e.target.value)} placeholder="작업명 또는 유형을 검색하세요"/>{q&&<button type="button" aria-label="검색어 지우기" onClick={()=>setQ("")}>×</button>}</div><select aria-label="작업 정렬" value={sort} onChange={e=>setSort(e.target.value)}><option>추천순</option><option>수익높은순</option><option>잔여많은순</option></select></section><div className="qj-types" aria-label="작업 유형">{types.map(x=><button type="button" aria-pressed={type===x} className={type===x?"active":""} onClick={()=>setType(x)} key={x}>{x}</button>)}</div><div className="qj-list-title"><div><h2>나에게 맞는 짧은 미션</h2><p>보상과 참여 조건을 확인하고 작업을 선택하세요.</p></div><span role="status" aria-live="polite">총 <b>{rows.length}</b>개</span></div><div className="qj-cards">{rows.map(x=><article className={"qj-task-card "+(x.status==="CLOSED"?"is-closed":"")} key={x.id}><div className="qj-task-top"><span className="qj-task-icon" aria-hidden="true">{icons[x.type]??"✓"}</span><span className="qj-task-category">{x.type}</span><span className={"qj-state "+(x.status==="OPEN"?"open":"closed")}>{x.status==="OPEN"?"참여가능":"모집 마감"}</span></div><h3><Link href={"/partner/quick/"+x.id}>{x.title}</Link></h3><p className="qj-task-description">{x.description}</p><div className="qj-task-metrics"><div><small>건당 보상</small><strong>{x.reward.toLocaleString("ko-KR")}<span>원</span></strong></div><div><small>{x.status==="OPEN"?"남은 수량":"모집 상태"}</small><b>{x.status==="OPEN"?x.remaining.toLocaleString("ko-KR")+"건":"종료"}</b></div></div><Link className="qj-task-action" href={"/partner/quick/"+x.id}>{x.status==="OPEN"?"조건 확인하고 참여하기":"상세 안내 보기"}<span aria-hidden="true">→</span></Link></article>)}{!rows.length&&<div className="qj-empty"><b>{items.length?"검색 조건에 맞는 작업이 없습니다.":"새로운 작업을 준비하고 있습니다."}</b><p>{items.length?"다른 검색어나 작업 유형을 선택해 주세요.":"모집이 시작되면 이곳에서 확인할 수 있습니다."}</p>{items.length>0&&<button type="button" onClick={()=>{setQ("");setType("전체");}}>전체 작업 보기</button>}</div>}</div></>
}
