import DashboardShell from "@/components/DashboardShell";
import PostingMarket,{type PostingItem} from "@/components/PostingMarket";
import Link from "next/link";
import {desc,eq,sql} from "drizzle-orm";import {getDb} from "@/db";import {campaigns,postingCampaigns} from "@/db/schema";
import "./posting-market.css";
export const dynamic="force-dynamic";
const nav=[{href:"/partner",label:"대시보드"},{href:"/partner/campaigns",label:"CPA 캠페인"},{href:"/partner/posting",label:"포스팅 광고"},{href:"/partner/posting/my",label:"내 포스팅"},{href:"/partner/earnings",label:"수익"},{href:"/partner/settlements",label:"정산"}];
async function loadCampaigns(){try{return await getDb().select({id:campaigns.id,name:campaigns.name,category:campaigns.category,description:campaigns.description,status:campaigns.status,endAt:campaigns.endAt,startAt:campaigns.startAt,mediaType:postingCampaigns.mediaType,totalSubmissionLimit:postingCampaigns.totalSubmissionLimit,perPartnerLimit:postingCampaigns.perPartnerLimit,partnerRate:sql<number|null>`(select partner_base_rate from campaign_rates where campaign_id=${campaigns.id} and effective_from<=now() and (effective_to is null or effective_to>now()) order by effective_from desc,created_at desc,id desc limit 1)`}).from(campaigns).innerJoin(postingCampaigns,eq(postingCampaigns.campaignId,campaigns.id)).where(sql`${campaigns.type}='POSTING' and ${campaigns.status} in ('ACTIVE','PAUSED','COMPLETED')`).orderBy(desc(campaigns.createdAt))}catch(error){console.error('Posting list failed',error);return null}}
export default async function Page(){const data=await loadCampaigns();if(!data)return <DashboardShell title="포스팅알바" nav={nav}><div className="pt-detail"><section className="pt-panel"><h1>포스팅알바</h1><p>현재 작업 목록을 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.</p><Link className="pt-button" href="/partner/posting">목록 다시 불러오기</Link></section></div></DashboardShell>;const now=new Date();const rows=data.map(x=>({...x,endAt:x.endAt?x.endAt.toISOString():null,isOpen:x.status==='ACTIVE'&&(!x.startAt||x.startAt<=now)&&(!x.endAt||x.endAt>now),stateLabel:x.status==='COMPLETED'||(x.endAt&&x.endAt<=now)?'모집 종료':x.status==='PAUSED'?'모집 중지':x.startAt&&x.startAt>now?'모집 예정':'모집 중'})) as PostingItem[];return <DashboardShell title="포스팅알바" description="콘텐츠를 작성하고 승인된 작업만큼 수익을 받아보세요." nav={nav}><div className="posting-market"><section className="posting-hero"><div><span>MY PICKUP · POSTING JOB</span><h1>글을 쓰는 시간이<br/><b>수익이 되는 포스팅알바</b></h1><p>블로그·카페·SNS 캠페인을 골라 가이드에 맞춰 작성하고 승인 후 수익을 받아보세요.</p><div><i>✓ 무료 참여</i><i>✓ 작업별 수익</i><i>✓ 투명한 검수</i></div></div><aside><small>현재 모집중</small><strong>{rows.filter(x=>x.isOpen).length}</strong><b>포스팅 캠페인</b></aside></section><section className="posting-guidebar"><b>포스팅알바</b><span>캠페인 선택</span><span>참여 신청</span><span>콘텐츠 작성</span><span>URL 제출</span><span>검수·정산</span></section><div className="pt-my-link"><Link href="/partner/posting/my">내 포스팅 · 제출 및 수정 요청 확인 →</Link></div><PostingMarket items={rows}/><section className="posting-bottom-guide"><div><small>처음이신가요?</small><h2>포스팅알바 참여 방법</h2></div><ol><li><b>01</b>캠페인 선택</li><li><b>02</b>참여 신청</li><li><b>03</b>콘텐츠 작성</li><li><b>04</b>URL 제출</li><li><b>05</b>승인·정산</li></ol></section></div></DashboardShell>}
