import { sql } from 'drizzle-orm';
import { getDb } from '@/db';
import { getCurrentUser } from '@/lib/auth/session';
export type Job={id:string;title:string;category:string;description:string;instructions:string;notice:string;target_url:string;reward:number;capacity:number;remaining:number;status:string};
export type Submission={id:string;job_id:string;title:string;partner_id:string;partner_name?:string;status:string;reward_snapshot:number;account:string|null;worked_at:string|null;note:string|null;reason:string|null;created_at:string;submitted_at:string|null;reviewed_at:string|null;proof_count:number};
export const partnerNav=[{href:'/partner',label:'대시보드'},{href:'/partner/campaigns',label:'CPA 캠페인'},{href:'/partner/posting',label:'포스팅 광고'},{href:'/partner/quick',label:'1초알바'},{href:'/partner/earnings',label:'수익'},{href:'/partner/settlements',label:'정산'}];
export const adminNav=[{href:'/admin',label:'대시보드'},{href:'/admin/campaigns',label:'캠페인 관리'},{href:'/admin/posting',label:'포스팅 작업'},{href:'/admin/quick',label:'1초알바 관리'},{href:'/admin/settlements',label:'정산'}];
export const labels:Record<string,string>={APPLIED:'참여중',SUBMITTED:'검수중',APPROVED:'승인 · 수익반영',REJECTED:'반려',DRAFT:'작성중',OPEN:'모집중',CLOSED:'마감'};
export async function quickReady(){const rows=await getDb().execute(sql`select to_regclass('public.quick_jobs') is not null and to_regclass('public.quick_submissions') is not null as ready`);return rows[0]?.ready===true;}
export async function listJobs(admin=false){return await getDb().execute(sql`select j.*, greatest(0,j.capacity-(select count(*) from quick_submissions s where s.job_id=j.id and s.status<>'REJECTED'))::int as remaining from quick_jobs j where ${admin} or j.status<>'DRAFT' order by j.created_at desc`) as unknown as Job[];}
export async function listSubmissions(partnerId?:string,jobId?:string,filter?:{q:string;status:string}){return await getDb().execute(sql`select s.id,s.job_id,j.title,s.partner_id,p.name as partner_name,s.status,s.reward_snapshot,s.account,s.worked_at,s.note,s.reason,s.created_at,s.submitted_at,s.reviewed_at,jsonb_array_length(s.proofs)::int as proof_count from quick_submissions s join quick_jobs j on j.id=s.job_id join partners p on p.id=s.partner_id where (${partnerId??null}::uuid is null or s.partner_id=${partnerId??null}::uuid) and (${jobId??null}::uuid is null or s.job_id=${jobId??null}::uuid) and (${filter?.q??""}='' or position(lower(${filter?.q??""}) in lower(j.title))>0) and (${filter?.status??""}='' or s.status::text=${filter?.status??""}) order by s.created_at desc,s.id desc limit 200`) as unknown as Submission[];}
export async function quickUser(admin=false){const u=await getCurrentUser();if(!u||u.status!=='ACTIVE'||(admin?!['ADMIN','SUPER_ADMIN'].includes(u.role):u.role!=='PARTNER'||!u.partnerId))throw new Error('UNAUTHORIZED');return u;}
export function quickError(e:unknown){const message=e instanceof Error?e.message:'';const known=['UNAUTHORIZED','INVALID_INPUT','INVALID_IMAGE','IMAGE_LIMIT','NOT_FOUND','CLOSED','FULL','LOCKED','REASON_REQUIRED','INVALID_ORIGIN','ORIGIN_CHECK_FAILED'];const code=known.includes(message)?message:'SERVICE_UNAVAILABLE';if(code==='SERVICE_UNAVAILABLE')console.error('Quick job request failed',e);return Response.json({ok:false,error:code},{status:code==='UNAUTHORIZED'?401:code==='NOT_FOUND'?404:code.includes('ORIGIN')?403:code==='SERVICE_UNAVAILABLE'?503:409});}
export function uuid(value:string){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value))throw new Error('NOT_FOUND');return value;}
