import DashboardShell from "@/components/DashboardShell";
import Link from "next/link";
import "../quick.css";

const nav=[{href:"/partner",label:"대시보드"},{href:"/partner/campaigns",label:"CPA 캠페인"},{href:"/partner/posting",label:"포스팅 광고"},{href:"/partner/quick",label:"1초알바"},{href:"/partner/earnings",label:"수익"},{href:"/partner/settlements",label:"정산"}];
const jobs:any={
"app-01":{title:"앱 설치 후 첫 화면 확인",type:"앱설치",reward:500,remaining:83,desc:"안내된 앱을 설치하고 지정된 첫 화면까지 진행한 뒤 완료 화면을 인증해 주세요."},
"app-02":{title:"신규 앱 설치 및 간단 체험",type:"앱설치",reward:700,remaining:42,desc:"앱 설치 후 안내된 기능을 간단히 체험하고 완료 화면을 등록합니다."},
"channel-01":{title:"공식 채널 구독 미션",type:"채널구독",reward:300,remaining:126,desc:"지정 채널을 구독하고 구독 완료 상태가 보이는 화면을 인증해 주세요."},
"video-01":{title:"짧은 영상 시청 참여",type:"영상시청",reward:250,remaining:215,desc:"안내된 콘텐츠를 시청하고 참여 조건을 완료한 화면을 등록합니다."},
"visit-01":{title:"서비스 페이지 방문 미션",type:"페이지방문",reward:200,remaining:310,desc:"지정 페이지를 방문해 안내된 미션을 수행하고 완료 정보를 제출합니다."},
"survey-01":{title:"간단 설문 참여",type:"설문",reward:600,remaining:67,desc:"짧은 설문 문항에 응답하고 제출 완료 화면을 인증해 주세요."},
"sns-01":{title:"SNS 계정 팔로우 미션",type:"SNS",reward:300,remaining:94,desc:"지정 SNS 계정을 팔로우하고 완료 상태를 인증해 주세요."}
};
export default async function Page({params}:{params:Promise<{id:string}>}){const {id}=await params;const j=jobs[id]||jobs["app-01"];return <DashboardShell title="1초알바" description="작업 조건을 확인하고 미션을 진행해 주세요." nav={nav}><main className="quick-market qj-detail"><div className="qj-breadcrumb"><Link href="/partner/quick">1초알바</Link><span>›</span><b>작업 상세</b></div><section className="qjd-card"><div className="qjd-icon">✓</div><div className="qjd-main"><span className="qjd-type">{j.type}</span><h1>{j.title}</h1><p>{j.desc}</p><div className="qjd-meta"><span>건당 수익 <b>{j.reward.toLocaleString("ko-KR")}원</b></span><span>잔여 수량 <b>{j.remaining.toLocaleString("ko-KR")}건</b></span><span>검수 방식 <b>관리자 확인</b></span></div></div><a href="#register" className="qjd-start">작업 등록하기</a></section><section className="qjd-tabs"><a href="#detail">상세내용</a><a href="#notice">유의사항</a><a href="#material">작업자료</a></section><section id="detail" className="qjd-section"><div className="qjd-label">DETAIL</div><h2>작업 상세내용</h2><div className="qjd-guide"><b>참여 방법</b><ol><li>작업 안내와 참여 조건을 먼저 확인합니다.</li><li>안내된 링크 또는 서비스에서 미션을 진행합니다.</li><li>완료 여부를 확인할 수 있는 화면을 캡처합니다.</li><li>아래 작업 등록 영역에서 작업 정보와 증빙을 제출합니다.</li><li>관리자 검수 승인 후 수익이 반영됩니다.</li></ol></div></section><section id="notice" className="qjd-section"><div className="qjd-label">NOTICE</div><h2>참여 전 꼭 확인하세요</h2><div className="qjd-warn"><p>동일 작업의 중복 참여, 조건 미충족, 식별할 수 없는 증빙 이미지는 승인되지 않을 수 있습니다.</p><p>작업별 인정 조건이 다르므로 미션을 시작하기 전에 상세 내용을 확인해 주세요.</p><p>허위 또는 타인의 인증 자료를 제출한 경우 참여가 제한될 수 있습니다.</p></div></section><section id="material" className="qjd-section"><div className="qjd-label">MATERIAL</div><h2>작업자료</h2><div className="qjd-material"><div><b>작업 링크</b><p>실제 운영 등록 시 관리자가 설정한 작업 링크가 표시됩니다.</p></div><button type="button">작업 링크 열기 ↗</button></div></section><section id="register" className="qjd-section qjd-register"><div className="qjd-label">SUBMIT</div><h2>작업 완료 등록</h2><p className="qjd-sub">미션 완료 후 아래 정보를 정확하게 입력해 주세요.</p><form><div className="qjd-fields"><label><span>작업 계정 / 아이디</span><input placeholder="미션에 사용한 계정 또는 아이디"/></label><label><span>작업 일시</span><input type="datetime-local"/></label><label className="wide"><span>작업 상세내용</span><textarea rows={5} placeholder="진행한 작업 내용을 간단히 입력해 주세요."/></label><label className="wide"><span>증빙 이미지</span><div className="qjd-upload"><b>완료 화면을 첨부해 주세요</b><small>JPG, PNG, WEBP · 실제 저장 기능은 운영 DB 연결 후 활성화됩니다.</small><input type="file" accept="image/*"/></div></label></div><label className="qjd-agree"><input type="checkbox"/> 입력한 작업 정보와 증빙 자료가 사실이며 검수 기준에 동의합니다.</label><button className="qjd-submit" type="button">작업 완료 등록</button><p className="qjd-demo">현재 화면은 UI 확인용입니다. DB 저장·검수·수익 반영 기능은 운영 데이터베이스 연결 후 활성화됩니다.</p></form></section></main></DashboardShell>}