import { sql } from 'drizzle-orm';
import { getDb } from '@/db';
import { quickUser,quickError,uuid } from '@/lib/quick';
import { requireSameOrigin } from '@/lib/security/origin';
export async function POST(request:Request){try{requireSameOrigin(request);await quickUser(true);const b=await request.json();
 const title=String(b.title??'').trim(),category=String(b.category??'').trim(),description=String(b.description??'').trim(),instructions=String(b.instructions??'').trim(),notice=String(b.notice??'').trim(),url=String(b.target_url??'').trim(),status=String(b.status??'DRAFT'),reward=Number(b.reward),capacity=Number(b.capacity);
 let parsed:URL;try{parsed=new URL(url);}catch{throw new Error('INVALID_INPUT');}
 if(!title||title.length>200||!category||category.length>40||!description||!instructions||!notice||[description,instructions,notice].some(x=>x.length>10000)||url.length>2000||!['http:','https:'].includes(parsed.protocol)||parsed.username||parsed.password||!['OPEN','DRAFT','CLOSED'].includes(status)||!Number.isSafeInteger(reward)||reward<1||reward>10000000||!Number.isSafeInteger(capacity)||capacity<1||capacity>1000000)throw new Error('INVALID_INPUT');
 const id=await getDb().transaction(async tx=>{if(b.id){const id=uuid(String(b.id));const rows=await tx.execute(sql`select id from quick_jobs where id=${id} for update`);if(!rows.length)throw new Error('NOT_FOUND');const used=await tx.execute(sql`select count(*)::int as n from quick_submissions where job_id=${id} and status<>'REJECTED'`);if(capacity<Number(used[0]?.n))throw new Error('FULL');await tx.execute(sql`update quick_jobs set title=${title},category=${category},description=${description},instructions=${instructions},notice=${notice},target_url=${url},reward=${reward},capacity=${capacity},status=${status},updated_at=now() where id=${id}`);return id;}
 const rows=await tx.execute(sql`insert into quick_jobs(title,category,description,instructions,notice,target_url,reward,capacity,status) values(${title},${category},${description},${instructions},${notice},${url},${reward},${capacity},${status}) returning id`);return rows[0].id;});return Response.json({ok:true,id});}catch(e){return quickError(e);}}
