import Link from "next/link";import "../finance.css";import DashboardShell from "@/components/DashboardShell";import SettlementRequest from "@/components/SettlementRequest";import {and,desc,eq,sql} from "drizzle-orm";import {getDb} from "@/db";import {requirePartner} from "@/lib/auth/guards";import {earnings,settlements} from "@/db/schema";
export const dynamic="force-dynamic";const labels:Record<string,string>={REQUESTED:"검토대기",APPROVED:"지급대기",PAID:"지급완료",REJECTED:"반려"};
const formatDate=(value:Date)=>value.toLocaleString("ko-KR",{timeZone:"Asia/Seoul"});
export default async function Page({searchParams}:{searchParams:Promise<{status?:string|string[]}>}){const raw=(await searchParams).status;const status=typeof raw==="string"&&(raw==="ALL"||Object.hasOwn(labels,raw))?raw:"ALL";const user=await requirePartner(),db=getDb();const[sum]=await db.select({available:sql<number>`coalesce(sum(case when ${earnings.status}='AVAILABLE' then ${earnings.amount} else 0 end),0)::int`,hold:sql<number>`coalesce(sum(case when ${earnings.status}='HOLD' then ${earnings.amount} else 0 end),0)::int`,paid:sql<number>`coalesce(sum(case when ${earnings.status}='PAID' then ${earnings.amount} else 0 end),0)::int`}).from(earnings).where(eq(earnings.partnerId,user.partnerId!));const available=Number(sum?.available??0);const rows=await db.select().from(settlements).where(eq(settlements.partnerId,user.partnerId!)).orderBy(desc(settlements.requestedAt));const filtered=rows.filter(r=>status==='ALL'||r.status===status);
return <DashboardShell title="출금 신청" nav={[{href:'/partner',label:'대시보드'},{href:'/partner/earnings',label:'수익'},{href:'/partner/settlements',label:'출금 신청'}]}><div className="partner-finance">
<header className="pf-head"><div><h1>출금 신청</h1><p>확정된 수익을 신청하고 지급 상태를 확인하세요.</p></div><Link href="/partner/earnings" className="pf-primary">수익 내역 보기 →</Link></header>
<section className="pf-stats" aria-label="출금 현황">{[['출금 가능',available,'지금 신청할 수 있는 금액','featured'],['출금 처리 중',sum?.hold,'검토·지급을 기다리는 금액',''],['지급 완료',sum?.paid,'지급이 완료된 수익','']].map(([label,amount,help,cls])=><div className={'pf-stat '+cls} key={String(label)}><span>{label}</span><strong>{Number(amount??0).toLocaleString('ko-KR')}원</strong><small>{help}</small></div>)}</section>
<div className="pf-flow" aria-label="출금 처리 순서"><span>1. 출금 신청</span><span>2. 관리자 검토</span><span>3. 승인 후 지급</span></div>
<SettlementRequest available={available}/>
<section className="pf-panel"><div className="pf-section-head"><div><h2>출금 신청 내역</h2><p>반려된 신청 금액은 다시 출금 가능한 수익으로 돌아갑니다.</p></div><span>{filtered.length}건</span></div>
<nav className="pf-filters" aria-label="출금 상태 필터">{Object.entries({ALL:'전체',...labels}).map(([key,label])=><Link key={key} href={'/partner/settlements?status='+key} aria-current={status===key?'page':undefined}>{label}</Link>)}</nav>
{filtered.length?filtered.map(r=><article className="pf-record" key={r.id}><div><span className={'pf-badge '+r.status}>{labels[r.status]??r.status}</span><h3>{r.settlementCode}</h3><p>신청 {formatDate(r.requestedAt)}</p>{r.paidAt?<p>지급 {formatDate(r.paidAt)}</p>:r.approvedAt?<p>승인 {formatDate(r.approvedAt)}</p>:null}{r.status==='REJECTED'?<p>신청 금액이 출금 가능한 수익으로 복구되었습니다.</p>:<p>{r.status==='PAID'?'지급 금액':'지급 예정 금액'} {r.paymentAmount.toLocaleString('ko-KR')}원</p>}</div><div className="pf-amount"><strong>{r.requestedAmount.toLocaleString('ko-KR')}원</strong><span className="pf-help">신청 금액</span></div></article>):<div className="pf-empty">{rows.length?'선택한 상태의 출금 신청이 없습니다.':'아직 출금 신청 내역이 없습니다.'}</div>}
</section></div></DashboardShell>}
