import {PGlite} from '@electric-sql/pglite';import {build} from 'esbuild';import {createRequire} from 'node:module';import {readFile,mkdir} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
const dir=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(dir,'../..'),require=createRequire(import.meta.url),{drizzle}=require('drizzle-orm/pglite');const pg=new PGlite();
for(const file of ['0000_initial','0001_advertiser_users','0002_notifications','0003_posting_finance','0004_cpa_accounting_guards','0005_audit_logs','0006_login_attempts','0007_quick_jobs','0008_customer_support'])await pg.exec((await readFile(path.join(repo,'db/migrations/'+file+'.sql'),'utf8')).replace('CREATE EXTENSION IF NOT EXISTS pgcrypto;',''));
const adapt=d=>new Proxy(d,{get(t,k){if(k==='execute')return async q=>(await t.execute(q)).rows;if(k==='transaction')return cb=>t.transaction(tx=>cb(adapt(tx)));const v=t[k];return typeof v==='function'?v.bind(t):v;}});globalThis.storyDb=adapt(drizzle(pg));globalThis.storyCookies=new Map();globalThis.storyCookieOptions=new Map();await mkdir(path.join(dir,'compiled'),{recursive:true});
async function load(file,name){const out=path.join(dir,'compiled',name+'.cjs');await build({entryPoints:[path.join(repo,file)],outfile:out,bundle:true,platform:'node',format:'cjs',packages:'external',jsx:'automatic',plugins:[{name:'fixtures',setup(b){b.onResolve({filter:/\.css$/},()=>({path:'css',namespace:'mock'}));b.onResolve({filter:/^@\/components\//},a=>({path:a.path,namespace:'mock'}));b.onResolve({filter:/^@\/db$/},()=>({path:'db',namespace:'mock'}));b.onResolve({filter:/^next\/headers$/},()=>({path:'cookies',namespace:'mock'}));b.onResolve({filter:/^next\/navigation$/},()=>({path:'nav',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:a.path==='css'?'':a.path==='@/components/DashboardShell'?'export default function Shell({children}){return children}':a.path.startsWith('@/components/')?'export default function Component(){return null}':a.path==='db'?'export function getDb(){return globalThis.storyDb}':a.path==='nav'?'export function redirect(p){throw new Error("REDIRECT:"+p)}':'export async function cookies(){return {get(n){const v=globalThis.storyCookies.get(n);return v===undefined?undefined:{value:v}},set(n,v,o){globalThis.storyCookies.set(n,v);globalThis.storyCookieOptions.set(n,o)}}}'}));b.onResolve({filter:/^@\//},a=>({path:path.join(repo,a.path.slice(2)+(a.path==='@/db/schema'?'/index.ts':'.ts'))}));}}]});return require(out);}

const {renderToStaticMarkup}=createRequire(path.join(repo,'package.json'))('react-dom/server');const session=await load('lib/auth/session.ts','adv-session');const ui=await load('lib/advertiser-ui.ts','adv-ui');assert.equal(ui.koreanPeriod(new Date('2026-10-01T00:30:00+09:00')).month.toISOString(),'2026-09-30T15:00:00.000Z');
const user=(await pg.query("insert into users(email,password_hash,role,status) values('adv@fixture.test','fixture','ADVERTISER','ACTIVE') returning id")).rows[0].id;const adv=(await pg.query("insert into advertisers(advertiser_code,company_name) values('ADV-ONE','본인회사') returning id")).rows[0].id;const other=(await pg.query("insert into advertisers(advertiser_code,company_name) values('ADV-TWO','다른회사') returning id")).rows[0].id;await pg.query('insert into advertiser_users(user_id,advertiser_id) values($1,$2)',[user,adv]);await session.createSession(user);
async function campaign(advertiser,type,code){return (await pg.query("insert into campaigns(campaign_code,advertiser_id,type,name,slug,status) values($1,$2,$3,$1,$1,'ACTIVE') returning id",[code,advertiser,type])).rows[0].id;}const cpa=await campaign(adv,'CPA','본인CPA'),post=await campaign(adv,'POSTING','본인포스팅'),foreign=await campaign(other,'CPA','외부캠페인');
await pg.query("insert into advertiser_ledger(advertiser_id,type,amount,description) values($1,'DEPOSIT',20000,'테스트충전'),($2,'DEPOSIT',99999,'외부충전')",[adv,other]);
for(let i=0;i<2;i++){const id=(await pg.query("insert into conversions(conversion_code,campaign_id,status,advertiser_rate_snapshot,partner_rate_snapshot,platform_margin_snapshot) values($1,$2,'APPROVED',2000,1000,1000) returning id",['CV-'+i,cpa])).rows[0].id;await pg.query("insert into advertiser_ledger(advertiser_id,conversion_id,type,amount,description) values($1,$2,'CPA_APPROVAL',-2000,'CPA차감')",[adv,id]);}await pg.query("insert into conversions(conversion_code,campaign_id,status,advertiser_rate_snapshot,partner_rate_snapshot,platform_margin_snapshot) values('REJECTED-FIXTURE',$1,'REJECTED',2000,1000,1000)",[cpa]);
const pu=(await pg.query("insert into users(email,password_hash,role,status) values('partner@fixture.test','fixture','PARTNER','ACTIVE') returning id")).rows[0].id;const partner=(await pg.query("insert into partners(user_id,partner_code,name) values($1,'P-FIXTURE','테스트파트너') returning id",[pu])).rows[0].id;const pc=(await pg.query("insert into posting_campaigns(campaign_id,media_type) values($1,'BLOG') returning id",[post])).rows[0].id;const pa=(await pg.query("insert into posting_applications(posting_campaign_id,partner_id,status) values($1,$2,'APPROVED') returning id",[pc,partner])).rows[0].id;const ps=(await pg.query("insert into posting_submissions(application_id,title,post_url,status) values($1,'승인된게시물','https://example.com/fixture','APPROVED') returning id",[pa])).rows[0].id;await pg.query("insert into advertiser_ledger(advertiser_id,posting_submission_id,type,amount,description) values($1,$2,'POSTING_APPROVAL',-3000,'포스팅차감')",[adv,ps]);await pg.query("insert into campaign_rates(campaign_id,advertiser_rate,partner_base_rate,effective_from) values($1,8000,4000,now()-interval '1 day'),($1,9000,5000,now()+interval '1 day')",[post]);
const campaigns=(await load('app/advertiser/campaigns/page.tsx','adv-campaigns')).default,ledger=(await load('app/advertiser/ledger/page.tsx','adv-ledger')).default,posting=(await load('app/advertiser/posting/page.tsx','adv-posting')).default,dashboard=(await load('app/advertiser/page.tsx','adv-dashboard')).default;let html=renderToStaticMarkup(await campaigns({searchParams:Promise.resolve({})}));assert(html.includes('4,000원'));assert(html.includes('3,000원'));assert(!html.includes('외부캠페인'));assert(!html.includes('/advertiser/reports'));assert(!html.includes('/advertiser/profile'));html=renderToStaticMarkup(await campaigns({searchParams:Promise.resolve({type:'POSTING',q:'본인'})}));assert(html.includes('본인포스팅'));assert(!html.includes('본인CPA'));html=renderToStaticMarkup(await campaigns({searchParams:Promise.resolve({q:'%'})}));assert(html.includes('조건에 맞는 캠페인이 없습니다'));
html=renderToStaticMarkup(await ledger({searchParams:Promise.resolve({type:'charge'})}));assert(html.includes('13,000원'));assert(html.includes('7,000원'));assert(!html.includes('외부충전'));assert(!html.includes('<td>테스트충전</td>'));html=renderToStaticMarkup(await ledger({searchParams:Promise.resolve({q:'포스팅'})}));assert(html.includes('포스팅차감'));assert(!html.includes('CPA차감'));
html=renderToStaticMarkup(await posting());assert.equal((html.match(/승인된게시물/g)||[]).length,1);assert(html.includes('3,000원'));assert(!html.includes('8,000원'));assert(!html.includes('9,000원'));assert(html.includes('실제 차감액'));
html=renderToStaticMarkup(await dashboard());assert(html.includes('오늘 접수 중 검수 대기</h3><p>0건'));assert(html.includes('7,000원'));assert(!html.includes('/advertiser/reports'));assert(html.includes('오늘 접수분 승인율'));
console.log('PASS: repeated equal CPA charges summed, posting spend included, advertiser isolation, campaign/ledger filters and literal search, full balance stats, actual approved posting charge, no scheduled-rate duplicates, rejected excluded from pending, KST month boundary, no dead nav');await pg.close();
