import {PGlite} from '@electric-sql/pglite';import {build} from 'esbuild';import {createRequire} from 'node:module';import {readFile,mkdir} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
const dir=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(dir,'../..'),require=createRequire(import.meta.url),{drizzle}=require('drizzle-orm/pglite');const pg=new PGlite();
for(const file of ['0000_initial','0001_advertiser_users','0002_notifications','0003_posting_finance','0004_cpa_accounting_guards','0005_audit_logs','0006_login_attempts','0007_quick_jobs','0008_customer_support'])await pg.exec((await readFile(path.join(repo,'db/migrations/'+file+'.sql'),'utf8')).replace('CREATE EXTENSION IF NOT EXISTS pgcrypto;',''));
const adapt=d=>new Proxy(d,{get(t,k){if(k==='execute')return async q=>(await t.execute(q)).rows;if(k==='transaction')return cb=>t.transaction(tx=>cb(adapt(tx)));const v=t[k];return typeof v==='function'?v.bind(t):v;}});globalThis.storyDb=adapt(drizzle(pg));globalThis.storyCookies=new Map();globalThis.storyCookieOptions=new Map();await mkdir(path.join(dir,'compiled'),{recursive:true});
async function load(file,name){const out=path.join(dir,'compiled',name+'.cjs');await build({entryPoints:[path.join(repo,file)],outfile:out,bundle:true,platform:'node',format:'cjs',packages:'external',jsx:'automatic',plugins:[{name:'fixtures',setup(b){b.onResolve({filter:/\.css$/},()=>({path:'css',namespace:'mock'}));b.onResolve({filter:/^@\/components\//},a=>({path:a.path,namespace:'mock'}));b.onResolve({filter:/^@\/db$/},()=>({path:'db',namespace:'mock'}));b.onResolve({filter:/^next\/headers$/},()=>({path:'cookies',namespace:'mock'}));b.onResolve({filter:/^next\/navigation$/},()=>({path:'nav',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:a.path==='css'?'':a.path==='@/components/DashboardShell'?'export default function Shell({children}){return children}':a.path.startsWith('@/components/')?'export default function Component(){return null}':a.path==='db'?'export function getDb(){return globalThis.storyDb}':a.path==='nav'?'export function redirect(p){throw new Error("REDIRECT:"+p)}':'export async function cookies(){return {get(n){const v=globalThis.storyCookies.get(n);return v===undefined?undefined:{value:v}},set(n,v,o){globalThis.storyCookies.set(n,v);globalThis.storyCookieOptions.set(n,o)}}}'}));b.onResolve({filter:/^@\//},a=>({path:path.join(repo,a.path.slice(2)+(a.path==='@/db/schema'?'/index.ts':'.ts'))}));}}]});return require(out);}

const {renderToStaticMarkup}=createRequire(path.join(repo,'package.json'))('react-dom/server');
const Home=(await load('app/page.tsx','home')).default;
let html=renderToStaticMarkup(await Home());assert(html.includes('현재 모집 중인 CPA 캠페인이 없습니다'));assert(html.includes('href="/partner/quick"'));assert(html.includes('href="/partner/earnings"'));assert(html.includes('href="/partner/signup"'));
const adv=(await pg.query("insert into advertisers(advertiser_code,company_name) values('HOME','fixture') returning id")).rows[0].id;
const cid=(await pg.query("insert into campaigns(campaign_code,advertiser_id,type,name,slug,status) values('HOME',$1,'CPA','실제캠페인','home','ACTIVE') returning id",[adv])).rows[0].id;
await pg.query("insert into campaign_rates(campaign_id,advertiser_rate,partner_base_rate,effective_from) values($1,2000,1000,now()-interval '1 day'),($1,9000,8000,now()+interval '1 day')",[cid]);
html=renderToStaticMarkup(await Home());assert(html.includes('실제캠페인'));assert(html.includes('1,000원'));assert(!html.includes('8,000원'));assert(html.includes('/partner/campaigns/'+cid));
await pg.query("update campaigns set end_at=now()-interval '1 day' where id=$1",[cid]);html=renderToStaticMarkup(await Home());assert(!html.includes('실제캠페인'));
await pg.query("update campaigns set end_at=null,start_at=now()+interval '1 day' where id=$1",[cid]);html=renderToStaticMarkup(await Home());assert(!html.includes('실제캠페인'));
await pg.query("update campaigns set start_at=null,status='PAUSED' where id=$1",[cid]);html=renderToStaticMarkup(await Home());assert(!html.includes('실제캠페인'));
const db=globalThis.storyDb;globalThis.storyDb={select(){throw new Error('fixture unavailable')}};const log=console.error;console.error=()=>{};try{html=renderToStaticMarkup(await Home());}finally{console.error=log;globalThis.storyDb=db;}assert(html.includes('캠페인을 불러오지 못했습니다'));assert(!html.includes('현재 모집 중인 CPA 캠페인이 없습니다'));
for(const file of ['app/about/page.tsx','app/about/advertiser/page.tsx']){const Page=(await load(file,file.includes('advertiser')?'home-ad-guide':'home-guide')).default;html=renderToStaticMarkup(await Page());assert(!html.includes('/images/guide/'));assert(!html.includes('bg-image-slot'));assert(html.includes(file.includes('advertiser')?'/customer/qna/write':'/partner/signup'));}
console.log('PASS: live campaigns, current reward, expired/future/paused exclusion, empty/error states, signup/quick/earnings and inquiry links');await pg.close();
