import {PGlite} from '@electric-sql/pglite';import {build} from 'esbuild';import {createRequire} from 'node:module';import {readFile,mkdir} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
const dir=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(dir,'../..'),require=createRequire(import.meta.url),{drizzle}=require('drizzle-orm/pglite');const pg=new PGlite();
for(const file of ['0000_initial','0001_advertiser_users','0002_notifications','0003_posting_finance','0004_cpa_accounting_guards','0005_audit_logs','0006_login_attempts','0007_quick_jobs','0008_customer_support'])await pg.exec((await readFile(path.join(repo,'db/migrations/'+file+'.sql'),'utf8')).replace('CREATE EXTENSION IF NOT EXISTS pgcrypto;',''));
const adapt=d=>new Proxy(d,{get(t,k){if(k==='execute')return async q=>(await t.execute(q)).rows;if(k==='transaction')return cb=>t.transaction(tx=>cb(adapt(tx)));const v=t[k];return typeof v==='function'?v.bind(t):v;}});globalThis.storyDb=adapt(drizzle(pg));globalThis.storyCookies=new Map();globalThis.storyCookieOptions=new Map();await mkdir(path.join(dir,'compiled'),{recursive:true});
async function load(file,name){const out=path.join(dir,'compiled',name+'.cjs');await build({entryPoints:[path.join(repo,file)],outfile:out,bundle:true,platform:'node',format:'cjs',packages:'external',jsx:'automatic',plugins:[{name:'fixtures',setup(b){b.onResolve({filter:/\.css$/},()=>({path:'css',namespace:'mock'}));b.onResolve({filter:/^@\/components\//},a=>({path:a.path,namespace:'mock'}));b.onResolve({filter:/^@\/db$/},()=>({path:'db',namespace:'mock'}));b.onResolve({filter:/^next\/headers$/},()=>({path:'cookies',namespace:'mock'}));b.onResolve({filter:/^next\/navigation$/},()=>({path:'nav',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:a.path==='css'?'':a.path==='@/components/DashboardShell'?'export default function Shell({children}){return children}':a.path.startsWith('@/components/')?'export default function Component(){return null}':a.path==='db'?'export function getDb(){return globalThis.storyDb}':a.path==='nav'?'export function redirect(p){throw new Error("REDIRECT:"+p)}':'export async function cookies(){return {get(n){const v=globalThis.storyCookies.get(n);return v===undefined?undefined:{value:v}},set(n,v,o){globalThis.storyCookies.set(n,v);globalThis.storyCookieOptions.set(n,o)}}}'}));b.onResolve({filter:/^@\//},a=>({path:path.join(repo,a.path.slice(2)+(a.path==='@/db/schema'?'/index.ts':'.ts'))}));}}]});return require(out);}


const {renderToStaticMarkup}=createRequire(path.join(repo,'package.json'))('react-dom/server');const session=await load('lib/auth/session.ts','member-session');const approval=await load('app/api/admin/partners/[id]/approve/route.ts','member-approve');const Page=(await load('app/admin/partners/page.tsx','member-page')).default,Advertisers=(await load('app/admin/advertisers/page.tsx','member-advertisers')).default;
const request=(origin='https://test.local')=>new Request('https://test.local/api',{method:'POST',headers:{origin,host:'test.local'}});const ctx=id=>({params:Promise.resolve({id})});
await assert.rejects(Page({searchParams:Promise.resolve({})}),/REDIRECT:\/login/);assert.equal((await approval.POST(request(),ctx('bad'))).status,401);
async function user(role,email,status='ACTIVE'){return (await pg.query("insert into users(email,password_hash,role,status) values($1,'fixture',$2,$3) returning id",[email,role,status])).rows[0].id;}
async function partner(status,code){const u=await user('PARTNER',code+'@fixture.test',status);const p=(await pg.query('insert into partners(user_id,partner_code,name) values($1,$2,$2) returning id',[u,code])).rows[0].id;return {u,p};}
const pending=await partner('PENDING','검증파트너'),suspended=await partner('SUSPENDED','중지파트너');await session.createSession(suspended.u);assert.equal((await approval.POST(request(),ctx(pending.p))).status,401);const normal=await partner('ACTIVE','일반파트너');await session.createSession(normal.u);await assert.rejects(Page({searchParams:Promise.resolve({})}),/REDIRECT:\//);assert.equal((await approval.POST(request(),ctx(pending.p))).status,403);
const admin=await user('ADMIN','admin@fixture.test');await session.createSession(admin);let html=renderToStaticMarkup(await Page({searchParams:Promise.resolve({status:'PENDING',q:'검증'})}));assert(html.includes('검증파트너'));assert(!html.includes('중지파트너'));html=renderToStaticMarkup(await Page({searchParams:Promise.resolve({q:'%'})}));assert(html.includes('조건에 맞는 파트너가 없습니다'));
assert.equal((await approval.POST(request('https://external.test'),ctx(pending.p))).status,403);assert.equal((await approval.POST(request(),ctx('bad'))).status,404);assert.equal((await approval.POST(request(),ctx(suspended.p))).status,409);
const results=await Promise.all([approval.POST(request(),ctx(pending.p)),approval.POST(request(),ctx(pending.p))]);assert.deepEqual(results.map(x=>x.status).sort(),[200,409]);assert.equal((await pg.query('select status from users where id=$1',[pending.u])).rows[0].status,'ACTIVE');assert.equal((await pg.query('select count(*)::int as n from audit_logs where target_id=$1',[pending.p])).rows[0].n,1);assert.equal((await pg.query('select status from users where id=$1',[suspended.u])).rows[0].status,'SUSPENDED');
await pg.query("insert into advertisers(advertiser_code,company_name,contract_status,representative_name) values('ADV-A','검증회사','ACTIVE','검증대표'),('ADV-B','종료회사','TERMINATED','다른대표')");html=renderToStaticMarkup(await Advertisers({searchParams:Promise.resolve({q:'검증대표',status:'ACTIVE'})}));assert(html.includes('검증회사'));assert(!html.includes('종료회사'));html=renderToStaticMarkup(await Advertisers({searchParams:Promise.resolve({q:'%'})}));assert(html.includes('조건에 맞는 광고주가 없습니다'));
const original=globalThis.storyDb;let selects=0;globalThis.storyDb={select(...args){if(selects++===0)return original.select(...args);throw new Error('fixture db failure')}};const log=console.error;console.error=()=>{};html=renderToStaticMarkup(await Page({searchParams:Promise.resolve({})}));assert(html.includes('목록을 불러오지 못했습니다'));assert(!html.includes('등록된 파트너가 없습니다'));selects=0;html=renderToStaticMarkup(await Advertisers({searchParams:Promise.resolve({})}));assert(html.includes('목록을 불러오지 못했습니다'));console.error=log;globalThis.storyDb=original;
const rollback=await partner('PENDING','롤백파트너');await pg.exec("CREATE FUNCTION fail_audit_fixture() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'fixture audit failure'; END $$; CREATE TRIGGER audit_fixture_failure BEFORE INSERT ON audit_logs FOR EACH ROW EXECUTE FUNCTION fail_audit_fixture();");console.error=()=>{};assert.equal((await approval.POST(request(),ctx(rollback.p))).status,500);console.error=log;assert.equal((await pg.query('select status from users where id=$1',[rollback.u])).rows[0].status,'PENDING');assert.equal((await pg.query('select approved_at from partners where id=$1',[rollback.p])).rows[0].approved_at,null);
console.log('PASS: audit failure rolls back approval, admin-only list, anonymous/inactive/partner approval denial, literal search and status filters, atomic concurrent approval, single audit record, suspended account preserved, invalid ID, origin check, advertiser representative search, load error distinct from empty');await pg.close();
