import {PGlite} from '@electric-sql/pglite';import {build} from 'esbuild';import {createRequire} from 'node:module';import {readFile,mkdir} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
const dir=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(dir,'../..'),require=createRequire(import.meta.url),{drizzle}=require('drizzle-orm/pglite');const pg=new PGlite();
for(const file of ['0000_initial','0001_advertiser_users','0002_notifications','0003_posting_finance','0004_cpa_accounting_guards','0005_audit_logs','0006_login_attempts','0007_quick_jobs','0008_customer_support'])await pg.exec((await readFile(path.join(repo,'db/migrations/'+file+'.sql'),'utf8')).replace('CREATE EXTENSION IF NOT EXISTS pgcrypto;',''));
const adapt=d=>new Proxy(d,{get(t,k){if(k==='execute')return async q=>(await t.execute(q)).rows;if(k==='transaction')return cb=>t.transaction(tx=>cb(adapt(tx)));const v=t[k];return typeof v==='function'?v.bind(t):v;}});globalThis.storyDb=adapt(drizzle(pg));globalThis.storyCookies=new Map();globalThis.storyCookieOptions=new Map();await mkdir(path.join(dir,'compiled'),{recursive:true});
async function load(file,name){const out=path.join(dir,'compiled',name+'.cjs');await build({entryPoints:[path.join(repo,file)],outfile:out,bundle:true,platform:'node',format:'cjs',packages:'external',plugins:[{name:'fixtures',setup(b){b.onResolve({filter:/^@\/db$/},()=>({path:'db',namespace:'mock'}));b.onResolve({filter:/^next\/headers$/},()=>({path:'cookies',namespace:'mock'}));b.onResolve({filter:/^next\/navigation$/},()=>({path:'nav',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:a.path==='db'?'export function getDb(){return globalThis.storyDb}':a.path==='nav'?'export function redirect(p){throw new Error("REDIRECT:"+p)}':'export async function cookies(){return {get(n){const v=globalThis.storyCookies.get(n);return v===undefined?undefined:{value:v}},set(n,v,o){globalThis.storyCookies.set(n,v);globalThis.storyCookieOptions.set(n,o)}}}'}));b.onResolve({filter:/^@\//},a=>({path:path.join(repo,a.path.slice(2)+(a.path==='@/db/schema'?'/index.ts':'.ts'))}));}}]});return require(out);}
const signup=await load('app/api/auth/partner-signup/route.ts','onboard-partner'),advSignup=await load('app/api/auth/advertiser-signup/route.ts','onboard-advertiser'),login=await load('app/api/auth/login/route.ts','onboard-login'),approval=await load('app/api/admin/advertisers/[id]/approve/route.ts','onboard-approve');const session=await load('lib/auth/session.ts','onboard-session');const {hashPassword}=await load('lib/auth/password.ts','onboard-password');
const queue=await load('lib/admin-advertiser-queue.ts','onboard-queue');
assert.deepEqual(queue.parseAdvertiserFilters({q:['bad'],status:'invalid',accountStatus:"PENDING' OR true --"}),{q:'',status:'ALL',accountStatus:'ALL'});
const request=b=>new Request('https://test.local/api',{method:'POST',headers:{origin:'https://test.local',host:'test.local','content-type':'application/json'},body:JSON.stringify(b)}),ctx=id=>({params:Promise.resolve({id})});
let r=await signup.POST(request({email:'partner@fixture.test',password:'Partner-fixture-password',name:'신규파트너',role:'ADMIN',status:'PENDING'}));assert.equal(r.status,201);let body=await r.json();assert.equal(body.status,'ACTIVE');assert.equal(body.sessionEstablished,true);let partner=await session.getCurrentUser();assert.equal(partner.role,'PARTNER');assert.equal(partner.status,'ACTIVE');assert.equal((await pg.query('select email_verified_at from users where id=$1',[partner.id])).rows[0].email_verified_at,null);assert.equal(globalThis.storyCookieOptions.get('olbarun_session').httpOnly,true);
assert.equal((await signup.POST(request({email:'partner@fixture.test',password:'Partner-fixture-password',name:'중복'}))).status,409);const token=globalThis.storyCookies.get('olbarun_session');assert.equal((await signup.POST(new Request('https://test.local/api',{method:'POST',headers:{origin:'https://other.test','content-type':'application/json'},body:'{}'}))).status,403);
const input={email:'advertiser@fixture.test',password:'Advertiser-fixture-password',companyName:'신청회사',name:'담당자',role:'ADMIN',status:'ACTIVE'};r=await advSignup.POST(request(input));assert.equal(r.status,201);body=await r.json();assert.equal(body.status,'PENDING');assert.equal(globalThis.storyCookies.get('olbarun_session'),token);const adv=(await pg.query('select * from advertisers')).rows[0];const adUser=(await pg.query("select * from users where email='advertiser@fixture.test'")).rows[0];assert.equal(adUser.role,'ADVERTISER');assert.equal(adUser.status,'PENDING');assert.equal((await advSignup.POST(request(input))).status,409);assert.equal((await pg.query('select count(*)::int as n from advertisers')).rows[0].n,1);r=await login.POST(request({email:input.email,password:input.password}));assert.equal(r.status,403);assert.equal((await r.json()).error,'APPROVAL_PENDING');assert.equal((await approval.POST(request({}),ctx(adv.id))).status,403);globalThis.storyCookies.clear();assert.equal((await approval.POST(request({}),ctx(adv.id))).status,401);
await pg.query("insert into advertisers(advertiser_code,company_name) values('ADV-NO-ACCOUNT','계정없는회사')");
assert.equal(await queue.countPendingAdvertisers(),1);
assert.equal((await queue.listAdminAdvertisers(queue.parseAdvertiserFilters({accountStatus:'PENDING',q:'신청회사',status:'LEAD'}))).length,1);
assert.equal((await queue.listAdminAdvertisers(queue.parseAdvertiserFilters({accountStatus:'PENDING',status:'ACTIVE'}))).length,0);
assert.equal((await queue.listAdminAdvertisers(queue.parseAdvertiserFilters({accountStatus:'NONE'}))).length,1);
assert.equal((await queue.listAdminAdvertisers(queue.parseAdvertiserFilters({q:"' OR true --"}))).length,0);
const admin=(await pg.query("insert into users(email,password_hash,role,status) values('admin@fixture.test',$1,'ADMIN','ACTIVE') returning id",[hashPassword('Admin-fixture-password')])).rows[0].id;await session.createSession(admin);r=await approval.POST(request({}),ctx(adv.id));assert.equal(r.status,200);assert.equal((await approval.POST(request({}),ctx(adv.id))).status,409);assert.equal((await pg.query("select count(*)::int as n from audit_logs where action='ADVERTISER_APPROVED'")).rows[0].n,1);r=await login.POST(request({email:input.email,password:input.password}));assert.equal(r.status,200);assert.equal((await session.getCurrentUser()).role,'ADVERTISER');
assert.equal(await queue.countPendingAdvertisers(),0);assert.equal((await queue.listAdminAdvertisers(queue.parseAdvertiserFilters({accountStatus:'ACTIVE'}))).length,1);
await pg.query("update users set status='SUSPENDED' where id=$1",[adUser.id]);await session.createSession(admin);assert.equal((await approval.POST(request({}),ctx(adv.id))).status,409);r=await login.POST(request({email:input.email,password:input.password}));assert.equal((await r.json()).error,'ACCOUNT_DISABLED');
await advSignup.POST(request({...input,email:'rollback@fixture.test'}));const nextAdv=(await pg.query('select advertiser_id from advertiser_users au join users u on u.id=au.user_id where u.email=$1',['rollback@fixture.test'])).rows[0].advertiser_id;await pg.exec("CREATE FUNCTION fail_onboarding_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'fixture audit failure'; END $$; CREATE TRIGGER onboarding_audit_failure BEFORE INSERT ON audit_logs FOR EACH ROW EXECUTE FUNCTION fail_onboarding_audit();");const log=console.error;console.error=()=>{};r=await approval.POST(request({}),ctx(nextAdv));console.error=log;assert.equal(r.status,500);assert.equal((await pg.query('select status from users where email=$1',['rollback@fixture.test'])).rows[0].status,'PENDING');await pg.exec('DROP TRIGGER onboarding_audit_failure ON audit_logs; DROP FUNCTION fail_onboarding_audit();');
// Existing pending partners adopt the new policy; suspended and advertiser accounts stay restricted.
await pg.query("update users set status='PENDING' where id=$1",[partner.id]);await pg.exec((await readFile(path.join(repo,'db/migrations/0009_partner_instant_signup.sql'),'utf8')));assert.equal((await pg.query('select status from users where id=$1',[partner.id])).rows[0].status,'ACTIVE');assert.equal((await pg.query('select status from users where id=$1',[adUser.id])).rows[0].status,'SUSPENDED');assert.equal((await pg.query('select status from users where email=$1',['rollback@fixture.test'])).rows[0].status,'PENDING');
assert.equal(await queue.countPendingAdvertisers(),1);assert.equal((await queue.listAdminAdvertisers(queue.parseAdvertiserFilters({accountStatus:'SUSPENDED'}))).length,1);
console.log('PASS: advertiser approval queue counts, account/contract/search filters, missing accounts, and SQL injection handling');
console.log('PASS: immediate partner access and session, unverified identity stays unverified, pending advertiser signup, duplicate rollback, origin/role guards, administrator approval, audit atomicity, suspended restriction and scoped partner migration');await pg.close();
