import DashboardShell from "@/components/DashboardShell";
import AdvertiserConversionReview from "@/components/AdvertiserConversionReview";
import { desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { campaigns, conversionData, conversions, partners } from "@/db/schema";
import { requireAdvertiser } from "@/lib/auth/advertiser";
import { decryptPii } from "@/lib/security/pii";
import { writeAudit } from "@/lib/audit";

export const dynamic="force-dynamic";
const nav=[{href:"/advertiser",label:"대시보드"},{href:"/advertiser/campaigns",label:"캠페인"},{href:"/advertiser/conversions",label:"전환 DB"},{href:"/advertiser/ledger",label:"광고비"}];
function formatPhone(value:string|null){if(!value)return "-";try{const p=decryptPii(value).replace(/\D/g,"");if(p.length===11)return `${p.slice(0,3)}-${p.slice(3,7)}-${p.slice(7)}`;if(p.length===10)return `${p.slice(0,3)}-${p.slice(3,6)}-${p.slice(6)}`;return p;}catch{return "복호화 오류";}}
export default async function Page(){const advertiser=await requireAdvertiser();const rows=await getDb().select({id:conversions.id,code:conversions.conversionCode,campaign:campaigns.name,status:conversions.status,customer:conversionData.customerName,phone:conversionData.customerPhoneEncrypted,region:conversionData.region,partner:partners.partnerCode,cost:conversions.advertiserRateSnapshot,submittedAt:conversions.submittedAt}).from(conversions).innerJoin(campaigns,eq(conversions.campaignId,campaigns.id)).leftJoin(conversionData,eq(conversionData.conversionId,conversions.id)).leftJoin(partners,eq(conversions.partnerId,partners.id)).where(eq(campaigns.advertiserId,advertiser.advertiserId)).orderBy(desc(conversions.submittedAt));if(rows.some(r=>Boolean(r.phone)))await writeAudit({actorUserId:advertiser.id,action:"PII_VIEW",targetType:"ADVERTISER_CONVERSION_LIST",targetId:advertiser.advertiserId,summary:`${advertiser.companyName} 전환 DB 개인정보 목록 열람`,metadata:{recordCount:rows.filter(r=>Boolean(r.phone)).length}});return <DashboardShell title="전환 DB" description="내 캠페인 DB를 확인하고 승인·거절 검수를 요청합니다." nav={nav}><section className="panel card"><div className="table-wrap"><table><thead><tr><th>접수번호</th><th>캠페인</th><th>고객</th><th>연락처</th><th>파트너</th><th>상태</th><th>광고비</th><th>접수일</th><th>검수요청</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{r.code}</td><td>{r.campaign}</td><td>{r.customer??"-"}<br/><span className="muted">{r.region??""}</span></td><td>{formatPhone(r.phone)}</td><td>{r.partner??"직접유입"}</td><td><span className="badge">{r.status}</span></td><td>{r.cost.toLocaleString("ko-KR")}원</td><td>{new Date(r.submittedAt).toLocaleString("ko-KR")}</td><td><AdvertiserConversionReview id={r.id} status={r.status}/></td></tr>):<tr><td colSpan={9} className="empty-cell">접수된 DB가 없습니다.</td></tr>}</tbody></table></div></section></DashboardShell>}
