import DashboardShell from "@/components/DashboardShell";
import { desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { requirePartner } from "@/lib/auth/guards";
import { campaigns, conversions } from "@/db/schema";

export const dynamic="force-dynamic";
const nav=[{href:"/partner",label:"대시보드"},{href:"/partner/campaigns",label:"CPA 캠페인"},{href:"/partner/conversions",label:"전환 실적"},{href:"/partner/earnings",label:"수익"},{href:"/partner/settlements",label:"정산"}];
const labels:Record<string,string>={RECEIVED:"접수",DELIVERED:"광고주 전달",REVIEWING:"승인 검수 중",APPROVED:"승인",REJECTED:"거절",REJECTION_REQUESTED:"거절 검수 중",DISPUTED:"이의 처리 중",CANCELLED:"취소",TEST:"테스트"};
const duplicateLabels:Record<string,string>={CLEAR:"정상",SUSPECTED:"중복 의심",DUPLICATE:"중복"};
const filters=["ALL","RECEIVED","DELIVERED","REVIEWING","APPROVED","REJECTED"];
export default async function PartnerConversionsPage({searchParams}:{searchParams:Promise<{status?:string;q?:string}>}){const user=await requirePartner();const p=await searchParams,status=filters.includes(p.status??"")?p.status!:"ALL",q=(p.q??"").trim().toLowerCase();const all=await getDb().select({id:conversions.id,code:conversions.conversionCode,campaign:campaigns.name,status:conversions.status,partnerRate:conversions.partnerRateSnapshot,duplicateStatus:conversions.duplicateStatus,submittedAt:conversions.submittedAt,approvedAt:conversions.approvedAt}).from(conversions).innerJoin(campaigns,eq(conversions.campaignId,campaigns.id)).where(eq(conversions.partnerId,user.partnerId!)).orderBy(desc(conversions.submittedAt));const rows=all.filter(r=>(status==="ALL"||r.status===status)&&(!q||r.code.toLowerCase().includes(q)||r.campaign.toLowerCase().includes(q)));const received=all.length,approved=all.filter(r=>r.status==="APPROVED").length,rejected=all.filter(r=>r.status==="REJECTED").length,pending=all.filter(r=>["RECEIVED","DELIVERED","REVIEWING","REJECTION_REQUESTED"].includes(r.status)).length;const decided=approved+rejected,approvalRate=decided?Math.round((approved/decided)*1000)/10:0;return <DashboardShell title="전환 실적" description="내 광고링크에서 발생한 CPA 접수·검수·승인 현황을 확인합니다." nav={nav}><section className="stats"><div className="panel stat"><span>전체 DB</span><strong>{received}</strong></div><div className="panel stat"><span>검수 진행</span><strong>{pending}</strong></div><div className="panel stat"><span>승인</span><strong>{approved}</strong></div><div className="panel stat"><span>확정 승인율</span><strong>{approvalRate}%</strong></div></section><section className="panel card"><form method="get" className="page-toolbar"><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{filters.map(f=><a key={f} className={`btn ${status===f?"primary":""}`} href={`/partner/conversions?status=${f}${q?`&q=${encodeURIComponent(q)}`:""}`}>{f==="ALL"?"전체":labels[f]}</a>)}</div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><input name="q" defaultValue={p.q??""} placeholder="접수번호·캠페인 검색"/><input type="hidden" name="status" value={status}/><button className="btn" type="submit">검색</button></div></form><div className="table-wrap"><table><thead><tr><th>접수일</th><th>접수번호</th><th>캠페인</th><th>상태</th><th>중복</th><th>예상/확정 수익</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{new Date(r.submittedAt).toLocaleString("ko-KR")}</td><td>{r.code}</td><td>{r.campaign}</td><td><span className="badge">{labels[r.status]??r.status}</span></td><td>{duplicateLabels[r.duplicateStatus]??r.duplicateStatus}</td><td><strong>{r.partnerRate.toLocaleString("ko-KR")}원</strong><br/><span className="muted">{r.status==="APPROVED"?"수익 확정":"승인 시 확정"}</span></td></tr>):<tr><td colSpan={6} className="empty-cell">조건에 맞는 전환 DB가 없습니다.</td></tr>}</tbody></table></div></section></DashboardShell>}
