import Link from "next/link";
import "../posting-market.css";
import DashboardShell from "@/components/DashboardShell";
import { desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { requirePartner } from "@/lib/auth/guards";
import { campaigns, postingApplications, postingCampaigns, postingReviews, postingSubmissions } from "@/db/schema";

export const dynamic="force-dynamic";
const nav=[{href:"/partner/posting",label:"← 포스팅 광고"},{href:"/partner/posting/my",label:"내 포스팅"}];
const labels:Record<string,string>={APPLIED:"참여신청",SUBMITTED:"검수대기",REVISION_REQUESTED:"수정요청",APPROVED:"승인완료",REJECTED:"거절",CANCELLED:"취소"};
async function loadRows(partnerId:string){return getDb().select({applicationId:postingApplications.id,applicationStatus:postingApplications.status,campaignName:campaigns.name,mediaType:postingCampaigns.mediaType,revisionLimit:postingCampaigns.revisionLimit,submissionId:postingSubmissions.id,submissionStatus:postingSubmissions.status,revisionCount:postingSubmissions.revisionCount,postUrl:postingSubmissions.postUrl,submittedAt:postingSubmissions.submittedAt,reviewReason:postingReviews.reason,reviewDecision:postingReviews.decision,reviewedAt:postingReviews.createdAt}).from(postingApplications).innerJoin(postingCampaigns,eq(postingApplications.postingCampaignId,postingCampaigns.id)).innerJoin(campaigns,eq(postingCampaigns.campaignId,campaigns.id)).leftJoin(postingSubmissions,eq(postingSubmissions.applicationId,postingApplications.id)).leftJoin(postingReviews,eq(postingReviews.submissionId,postingSubmissions.id)).where(eq(postingApplications.partnerId,partnerId)).orderBy(desc(postingApplications.appliedAt),desc(postingSubmissions.submittedAt),desc(postingReviews.createdAt));}
export default async function MyPostingPage(){const user=await requirePartner();const raw=await loadRows(user.partnerId!);const seen=new Set<string>();const rows=raw.filter(r=>{if(seen.has(r.applicationId))return false;seen.add(r.applicationId);return true});return <DashboardShell title="포스팅알바" description={`${user.partnerName??user.email}님의 참여 작업과 제출·수정 상태입니다.`} nav={nav}><div className="pt-detail pt-history"><header className="pt-panel"><h1>내 포스팅</h1><p>참여한 작업의 제출·검수·수정 요청을 확인하세요.</p><Link className="pt-back" href="/partner/posting">참여할 포스팅 작업 찾기 →</Link></header><section className="pt-panel"><div className="table-wrap"><table><thead><tr><th>캠페인</th><th>매체</th><th>상태</th><th>검수 의견</th><th>게시 URL</th><th>관리</th></tr></thead><tbody>{rows.length?rows.map(row=>{const status=row.submissionStatus??row.applicationStatus;const canSubmit=!["REJECTED","CANCELLED"].includes(row.applicationStatus)&&(!row.submissionId||(status==="REVISION_REQUESTED"&&(row.revisionCount??0)<row.revisionLimit));return <tr key={row.applicationId}><td data-label="캠페인"><strong>{row.campaignName}</strong></td><td data-label="매체">{row.mediaType}</td><td data-label="상태"><span className="badge">{labels[status]??status}</span>{row.submissionId?<div className="muted">수정 {row.revisionCount}/{row.revisionLimit}</div>:null}</td><td data-label="검수 의견">{row.reviewReason?<><strong>{row.reviewDecision==="REVISION_REQUESTED"?"수정 사유":"검수 사유"}</strong><br/>{row.reviewReason}{row.reviewedAt?<div className="muted">{row.reviewedAt.toLocaleString("ko-KR",{timeZone:"Asia/Seoul"})}</div>:null}</>:"-"}</td><td data-label="게시 URL">{row.postUrl?<a href={row.postUrl} target="_blank" rel="noopener noreferrer">게시물 보기</a>:"-"}</td><td data-label="관리">{canSubmit?<a className="btn" href={`/partner/posting/submit/${row.applicationId}`}>{row.submissionId?"수정본 제출":"작업결과 등록"}</a>:<span className="muted">{status==="SUBMITTED"?"검수 대기 중":status==="APPROVED"?"작업 완료":"제출 불가"}</span>}</td></tr>}):<tr><td colSpan={6} className="empty-cell">참여 중인 포스팅 작업이 없습니다.</td></tr>}</tbody></table></div></section></div></DashboardShell>}
