import Link from 'next/link';
import type {CSSProperties} from 'react';
import '../cpa/cpa-guide.css';
import './posting-guide.css';
export const metadata={title:'포스팅 알바란? 참여·작성·검수 가이드 | 마이픽업',description:'캠페인 신청부터 콘텐츠 작성, 게시물 URL 제출과 검수까지. 처음 시작하는 파트너를 위한 마이픽업 포스팅 안내.',alternates:{canonical:'/about/posting'}};
function Icon({name}:{name:string}){const paths:Record<string,React.ReactNode>={target:<><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><path d="m12 12 8-8M16 4h4v4"/></>,link:<><path d="m10 13 4-4M8 15l-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m2 3 1-1a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0"/></>,megaphone:<><path d="M4 10v5h4l11 4V5L8 10H4Zm4 5 2 6h4l-2-5M22 9v6"/></>,check:<><path d="m8 12 3 3 5-6"/><path d="m12 2 8 3v6c0 5-4 9-8 11-4-2-8-6-8-11V5Z"/></>,wallet:<><rect x="3" y="5" width="18" height="15" rx="3"/><path d="M3 8h18m0 4h-6v5h6M5 5V3h12"/><path d="M17 14.5h.01"/></>,copy:<><rect x="8" y="8" width="12" height="13" rx="2"/><path d="M15 8V3H3v13h5"/></>,pin:<><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 0 1 14 0Z"/><circle cx="12" cy="10" r="2"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></>,globe:<><circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/></>,alert:<><path d="m12 3 10 18H2Z"/><path d="M12 9v5m0 3h.01"/></>,arrow:<path d="M4 12h16m-6-6 6 6-6 6"/>,list:<><rect x="4" y="3" width="16" height="18" rx="3"/><path d="M8 8h8m-8 4h8m-8 4h5"/></>};return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]??paths.check}</svg>}
const steps=[['target','광고 선택','승인 수익, 모집 수량, 채널과 마감일을 비교하고 상세 가이드를 확인하세요.'],['list','참여 신청','참여 조건을 확인해 신청한 뒤, 내 포스팅에서 해당 작업을 확인하세요.'],['megaphone','콘텐츠 작성','필수 키워드, 글자 수와 이미지 조건에 맞게 콘텐츠를 직접 작성하세요.'],['link','게시·URL 제출','지정된 매체에 공개한 뒤 제목과 실제 게시물 URL을 제출하세요.'],['wallet','검수·수익 확인','승인되면 수익이 반영됩니다. 수정 요청이 있다면 수정 후 다시 제출하세요.']];
const checks=[['globe','참여 채널','블로그·카페·SNS 등 캠페인에서 허용한 매체'],['wallet','승인 수익','게시물 1건이 최종 승인됐을 때 반영되는 금액'],['list','작성 기준','필수 키워드, 최소 글자 수, 이미지와 포함 내용'],['target','모집·참여 제한','전체 모집 수량과 회원 1인당 가능한 참여 건수'],['clock','게시물 유지','승인 후에도 공개 상태를 유지해야 하는 기간'],['check','수정·반려 조건','수정 요청에 대응할 수 있는 횟수와 반려 기준']];
const faq=[['글을 올리면 바로 수익이 생기나요?','게시만으로는 수익이 확정되지 않습니다. 게시물 URL을 제출하고 캠페인의 작성 기준에 따라 검수 승인을 받아야 수익에 반영됩니다.'],['처음 가입하면 바로 참여할 수 있나요?','광고 목록은 가입 전에도 볼 수 있습니다. 파트너는 별도 승인 없이 가입 후 로그인하여 참여와 제출을 진행합니다.'],['기존에 작성한 글을 제출해도 되나요?','캠페인마다 다릅니다. 신규 작성 여부와 게시 기간 등 상세 가이드를 확인하고 조건에 맞는 게시물만 제출하세요.'],['수정 요청을 받으면 어떻게 하나요?','내 포스팅에서 요청 내용을 확인하고 게시물을 수정하세요. 이후 같은 제출 화면에서 다시 제출하면 됩니다. 캠페인별 수정 횟수와 안내 조건을 확인해 주세요.'],['여러 캠페인에 참여할 수 있나요?','캠페인별 모집 수량과 1인 참여 제한에 따라 달라집니다. 각 캠페인의 참여 조건을 확인해 주세요.']];
export default function Page(){return <main className="cpa-refresh posting-refresh">
<nav className="cr-subnav" aria-label="이용 안내"><div className="container"><Link href="/about">초보자 가이드</Link><Link href="/about/cpa">CPA 알바</Link><Link href="/about/posting" aria-current="page">포스팅 알바</Link><Link href="/about/advertiser">광고주 가이드</Link></div></nav>
<section className="cr-hero"><div className="container cr-hero-grid"><div className="cr-hero-copy"><span className="cr-eyebrow"><span/>처음 시작하는 포스팅 가이드</span><h1>나의 콘텐츠가,<br/><em>승인된 수익이 되도록.</em></h1><p>캠페인의 가이드에 맞춰 작성하고,<br/>게시물 URL을 제출하면 검수가 시작됩니다.<br/>첫 작업에 필요한 준비를 함께 알아보세요.</p><div className="cr-actions"><Link className="cr-button primary" href="/partner/posting">포스팅 광고 둘러보기<Icon name="arrow"/></Link><a className="cr-button secondary" href="#posting-how-to">참여 방법 보기</a></div><small>파트너는 별도 승인 없이 가입 후 참여·제출할 수 있습니다.</small></div>
<div className="pr-editor" aria-label="포스팅 작성 흐름 예시"><div className="pr-editor-bar"><span className="pr-editor-dots" aria-hidden="true"><i/><i/><i/></span><span>CONTENT STUDIO</span><span className="cr-demo-tag">작성 흐름 예시</span></div><div className="pr-editor-sheet"><span className="pr-sheet-label"><Icon name="list"/>나의 캠페인 콘텐츠</span><b>정보는 정확하게,<br/>이야기는 나답게.</b><div className="pr-picture" aria-hidden="true"><Icon name="megaphone"/><span>나만의 콘텐츠</span></div><div className="pr-lines" aria-hidden="true"><i/><i/><i/></div><div className="pr-editor-checks">{['가이드 확인','직접 작성','URL 제출'].map((x,i)=><span key={x} style={{'--i':i} as CSSProperties}><Icon name="check"/>{x}</span>)}</div></div><div className="pr-review-note"><Icon name="wallet"/><div><b>검수 승인 후 수익 반영</b><p>작성·제출만으로 수익이 확정되지는 않아요.</p></div></div></div></div></section>
<section className="container cr-section cr-intro"><div><span className="cr-kicker">01 · 핵심 이해</span><h2>가이드가 있는 콘텐츠 작업이에요.</h2></div><p>광고주가 정한 조건에 맞춰 블로그·카페·SNS 등에 게시물을 작성하는 활동입니다. <strong>참여 신청 → 콘텐츠 작성 → URL 제출 → 검수 승인</strong>을 거쳐 수익이 반영됩니다.</p><div className="cr-example"><Icon name="megaphone"/><div><b>예를 들어 서비스 소개 캠페인이라면</b><p>필수 키워드와 이미지 조건을 확인해 직접 글을 작성합니다. 지정된 매체에 공개하고 URL을 제출한 뒤, 작성 기준에 맞는지 검수받아요.</p></div></div></section>
<section className="cr-tinted" id="posting-how-to"><div className="container cr-section"><div className="cr-section-head"><div><span className="cr-kicker">02 · 참여 순서</span><h2>첫 포스팅은 이 다섯 단계로.</h2></div><p>작성 전에 신청하고,<br/>게시 후에는 URL을 제출하세요.</p></div><ol className="cr-steps">{steps.map((s,i)=><li key={s[1]}><span className="cr-step-number">STEP 0{i+1}</span><span className="cr-icon"><Icon name={s[0]}/></span><h3>{s[1]}</h3><p>{s[2]}</p></li>)}</ol><div className="cr-shortcuts"><div><b>제출과 수정은 ‘내 포스팅’에서.</b><p>참여한 작업을 열어 제목·URL을 제출하고 검수 결과를 확인하세요.</p></div><div><Link href="/partner/posting/my">내 포스팅<Icon name="arrow"/></Link><Link href="/partner/earnings">수익확인<Icon name="arrow"/></Link></div></div></div></section>
<section className="container cr-section"><span className="cr-kicker">03 · 작성 전 체크</span><h2>글을 쓰기 전에, 이 조건부터.</h2><p className="cr-section-lead">수익과 함께 작성 분량, 채널과 유지 기간까지 비교해 주세요.</p><div className="cr-checks">{checks.map(x=><article key={x[1]}><span className="cr-icon"><Icon name={x[0]}/></span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></section>
<section className="pr-submit-section"><div className="container cr-section"><div className="cr-section-head"><div><span className="cr-kicker">04 · 제출 준비</span><h2>제출 전, 한 번만 더 확인하세요.</h2></div><p>캠페인의 상세 가이드가 우선입니다.<br/>아래 항목을 마지막으로 확인해 주세요.</p></div><div className="pr-submit-grid">{[['list','필수 내용','키워드와 안내 내용이 빠지지 않았나요?'],['megaphone','작성 분량','글자 수와 이미지 조건을 충족했나요?'],['globe','공개 상태','제출할 URL이 열리고 게시물이 공개되어 있나요?'],['clock','유지·수정','게시물 유지 기간과 수정 조건을 확인했나요?']].map((x,i)=><article key={x[1]}><span className="pr-check-number">0{i+1}</span><Icon name={x[0]}/><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><aside className="pr-revision"><Icon name="copy"/><div><h3>수정 요청을 받았다면?</h3><p>내 포스팅에서 요청 내용 확인 → 게시물 수정 → 같은 제출 화면에서 다시 제출. 캠페인의 수정 횟수와 안내된 조건 안에서 진행하세요.</p></div><Link href="/partner/posting/my">작업 확인<Icon name="arrow"/></Link></aside><aside className="cr-warning"><Icon name="alert"/><div><h3>직접 작성한, 정확한 콘텐츠로 참여하세요.</h3><p>복사·도용한 콘텐츠, 사실과 다른 과장 표현과 금지된 방식은 승인에 영향을 줄 수 있습니다. 다른 참여자의 글을 그대로 사용하지 마세요.</p></div></aside></div></section>
<section className="container cr-section cr-faq"><div><span className="cr-kicker">05 · 자주 묻는 질문</span><h2>첫 작업 전,<br/>궁금한 것부터.</h2><p>도움이 필요하다면<br/><Link href="/customer/qna/write">1:1 문의로 알려주세요 →</Link></p></div><div>{faq.map((x,i)=><details key={x[0]} open={i===0}><summary>{x[0]}<span aria-hidden="true">+</span></summary><p>{x[1]}</p></details>)}</div></section>
<section className="container cr-end"><span className="cr-icon"><Icon name="megaphone"/></span><h2>내 채널에 맞는 첫 광고를 찾아보세요.</h2><p>참여 조건을 확인하고, 내가 잘 쓸 수 있는 주제부터 시작하세요.</p><div className="cr-actions"><Link className="cr-button primary" href="/partner/posting">포스팅 광고 보기<Icon name="arrow"/></Link><Link className="cr-button secondary" href="/partner/signup">파트너 회원가입</Link></div></section>
</main>}
